namespace LsbDatabaseApi.@struct
{
    public enum ItemId
    {
        QUADAV_AUGURY_SHELL = 494,              // クゥダフの卜占甲
        QUADAV_CHARM = 495,                     // クゥダフの呪符
        CLUMP_OF_GAUSEBIT_WILDGRASS = 534,      // ゴゼビの野草
        ADVENTURER_COUPON = 536,                // 冒険者優待券
        BLOODY_ROBE = 540,                      // 血染めの衣
        CUP_OF_DHALMEL_SALIVA = 541,            // ダルメルの唾液
        WILD_RABBIT_TAIL = 542,                 // 野兎の尻尾
        DELKFUTT_KEY = 549,                     // デルクフのカギ
        METEORITE = 582,                        // 隕石
        PIECE_OF_ANCIENT_PAPYRUS = 1088,        // 古代魔法のパピルス
        CLUMP_OF_EXORAY_MOLD = 1089,            // エクソレイの粘菌
        CHUNK_OF_BOMB_COAL = 1090,              // ボムの炭
        UGGALEPIH_KEY = 1136,                   // ウガレピのカギ
        UNLIT_LANTERN = 1138,                   // 消えたランタン
        RANCOR_FLAME = 1139,                    // 怨みの炎
        JUDGMENT_KEY = 1142,                    // 裁きのカギ
        CURSED_KEY = 1143,                      // 呪われたカギ
        CLUMP_OF_GOOBBUE_HUMUS = 1181,          // グゥーブーの腐葉土
        SEALION_CREST_KEY = 1658,               // 海獅子の紋章のカギ
        CORAL_CREST_KEY = 1659,                 // 珊瑚の紋章のカギ
        BRONZE_KEY = 1660,                      // 青銅のカギ
        GOLD_KEY = 1684,                        // 黄金のカギ
        CLUSTER_CORE = 1667,                    // クラスターの魂
        RECOLLECTION_OF_PAIN = 1688,            // 悩ましき記憶の一塊
        HIPPOGRYPH_TAILFEATHER = 1690,          // ヒポグリフの尾羽根
        GIANT_SCALE = 1691,                     // 巨大な鱗
        CARMINE_CHIP = 1692,                    // カーマインチップ
        CYAN_CHIP = 1693,                       // シアンチップ
        GRAY_CHIP = 1694,                       // グレーチップ
        SNOW_LILY = 1725,                       // スノーリリー
        VIAL_OF_JODYS_ACID = 2307,              // ジョディの消化液
        GNOLE_CLAW = 2521,                      // ノールの爪
        PLUME_DOR = 2528,                       // 金の羽根
        TREMORSTONE = 2796,                     // 震動石
        SLICE_OF_COEURL_MEAT = 4377,            // クァールの肉
        BOTTLE_OF_HYSTEROANIMA = 5262,          // 迷のアニマ
        CHUNK_OF_SHUMEYO_SALT = 5267,           // シュ・メーヨ海の塩
        MISTMELT = 5265,                        // 雲消霧散石
        RUSTY_DAGGER = 16447,                   // 錆びた短剣
        ONE_HUNDRED_EIGHT_KNOT_QUIPU = 2562,    // 百八結節のキープス
        ROLANBERRY = 4365,                      // ロランベリー
        CIPHER_OF_SEMIHS_ALTER_EGO = 10157,     // 盟-セミ
        CURSE_WAND = 17437,                     // 呪術の杖
    }

    public enum KeyItemId
    {
        AIRSHIP_PASS_FOR_KAZHAM = 9,            // カザム行き飛空艇パス
        MAGICITE_OPTISTONE = 14,                // 魔晶石・メノ石
        MAGICITE_AURASTONE = 15,                // 魔晶石・ミノ石
        MAGICITE_ORASTONE = 16,                 // 魔晶石・クノ石
        FOOD_OFFERING = 17,                     // 献上品・食料品
        DRINK_OFFERING = 18,                    // 献上品・飲み物
        YAGUDO_TORCH = 20,                      // ヤグードの松明
        CREST_OF_DAVOI = 21,                    // ダボイ村紋章
        CORUSCANT_ROSARY = 46,                  // 妖光の数珠
        BLACK_MATINEE_NECKLACE = 47,            // 漆黒のマチネー
        TENSHODO_MEMBERS_CARD = 118,            // 天晶堂会員証
        TENSHODO_APPLICATION_FORM = 121,        // 天晶堂入会申込書
        WHITE_ORB = 131,                        // 白のオーブ
        PINK_ORB = 132,                         // ピンクのオーブ
        RED_ORB = 133,                          // 赤のオーブ
        BLOOD_ORB = 134,                        // 血のオーブ
        CURSED_ORB = 135,                       // 呪いのオーブ
        CRIMSON_ORB = 136,                      // 深紅のオーブ
        PORTAL_CHARM = 195,                     // 魔封門の札
        ROUND_FRIGICITE = 222,                  // 丸い氷石
        SQUARE_FRIGICITE = 223,                 // 四角い氷石
        TRIANGULAR_FRIGICITE = 224,             // 六角形の氷石
        FIRE_FRAGMENT = 239,                    // 炎の祈り
        WATER_FRAGMENT = 240,                   // 水の祈り
        EARTH_FRAGMENT = 241,                   // 土の祈り
        WIND_FRAGMENT = 242,                    // 風の祈り
        LIGHTNING_FRAGMENT = 243,               // 雷の祈り
        ICE_FRAGMENT = 244,                     // 氷の祈り
        LIGHT_FRAGMENT = 245,                   // 光の祈り
        OPTISTERY_RING = 250,                   // 目の院の指輪	
        PAINTBRUSH_OF_SOULS = 272,              // 魂の絵筆
        OLD_RUSTY_KEY = 273,                    // 古びた小さなカギ
        AURASTERY_RING = 276,                   // 耳の院の指輪
        RHINOSTERY_RING = 280,                  // 鼻の院の指輪
        ORCISH_CREST = 336,                     // オークの紋章
        QUADAV_CREST = 337,                     // クゥダフの紋章
        YAGUDO_CREST = 338,                     // ヤグードの紋章
        HOLLA_GATE_CRYSTAL = 352,               // ホラのゲートクリスタル
        DEM_GATE_CRYSTAL = 353,                 // デムのゲートクリスタル
        MEA_GATE_CRYSTAL = 354,                 // メアのゲートクリスタル
        PROMYVION_HOLLA_SLIVER = 358,           // プロミヴォン-ホラの黒水晶
        PROMYVION_DEM_SLIVER = 359,             // プロミヴォン-デムの黒水晶
        PROMYVION_MEA_SLIVER = 360,             // プロミヴォン-メアの黒水晶
        SCRAP_OF_PAPYRUS = 451,                 // パピルスの切れ端
        SHARD_OF_APATHY = 455,                  // 無知のかけら
        SHARD_OF_ARROGANCE = 456,               // 驕慢のかけら
        SHARD_OF_COWARDICE = 457,               // 怯懦のかけら
        SHARD_OF_ENVY = 458,                    // 嫉妬のかけら
        SHARD_OF_RAGE = 459,                    // 憎悪のかけら
        ANCIENT_VERSE_OF_ROMAEVE = 478,         // 古代の曲～ロ・メーヴ～
        ANCIENT_VERSE_OF_ALTEPA = 479,          // 古代の曲～ウガレピ～
        ANCIENT_VERSE_OF_UGGALEPIH = 480,       // 古代の曲～アルテパ～
        HYDRA_CORPS_COMMAND_SCEPTER = 486,      // ハイドラ戦隊指揮杖
        HYDRA_CORPS_EYEGLASS = 487,             // ハイドラ戦隊遠眼鏡
        HYDRA_CORPS_LANTERN = 488,              // ハイドラ戦隊角灯
        HYDRA_CORPS_TACTICAL_MAP = 489,         // ハイドラ戦隊作戦図
        HYDRA_CORPS_INSIGNIA = 490,             // ハイドラ戦隊識別標
        HYDRA_CORPS_BATTLE_STANDARD = 491,      // ハイドラ戦隊軍旗
        VIAL_OF_SHROUDED_SAND = 492,            // 朧なる砂
        RELIQUIARIUM_KEY = 582,                 // 礼拝堂宝物庫のカギ
        MIMEO_JEWEL = 586,                      // 再生の玉
        MIMEO_FEATHER = 587,                    // 再生の羽
        LIGHT_OF_HOLLA = 590,                   // ホラの輝き
        LIGHT_OF_DEM = 591,                     // デムの輝き
        LIGHT_OF_MEA = 592,                     // メアの輝き
        LIMIT_BREAKER = 606,                    // リミットブレーカー
        DELKFUTT_RECOGNITION_DEVICE = 613,      // デルクフ解除キー
        LETTERS_FROM_ULMIA_AND_PRISHE = 701,    // プリッシュたちの手紙
        BRAND_OF_DAWN = 710,                    // 暁の印
        BRAND_OF_TWILIGHT = 711,                // 黄昏の印
        SUPPLIES_PACKAGE = 775,                 // 不滅隊への差し入れ
        EPHRAMADIAN_GOLD_COIN = 786,            // イフラマド金貨
        NYZUL_ISLE_ROUTE = 898,                 // ナイズル島ルートメモ
        BATTLE_RATIONS = 917,                   // エドゥアルト塔への小包
        RED_RECOMMENDATION_LETTER = 921,        // 紅の紹介状
        BLUE_RECOMMENDATION_LETTER = 922,       // 蒼の紹介状
        GREEN_RECOMMENDATION_LETTER = 923,      // 翠の紹介状
        CHARRED_PROPELLER = 950,                // 亜麻布付きの木片
        PIECE_OF_SHATTERED_LUMBER = 951,        // クリスタル付きの木片
        OXIDIZED_PLATE = 952,                   // 刻印付きの木片
        SMALL_STARFRUIT = 958,                  // 小さな星の木の実
        MINE_SHAFT_KEY = 961,                   // 鉱山の坑道のカギ
        VUNKERL_HERB = 966,                     // ブンカール浦薬草
        VUNKERL_HERB_MEMO = 967,                // ブンカール浦薬草メモ
        FORT_KEY = 974,                         // ワームキー
        SILVERMINE_KEY = 988,                   // 銀山の廃坑のカギ
        CONQUEST_PROMOTION_VOUCHER = 1060,      // コンクェスト奨励特別券
        ORCISH_WARMACHINE_BODY = 1019,          // オーク戦車の装甲
        NUMBER_EIGHT_SHELTER_KEY = 1051,        // 8番壕のカギ
        DELKFUTT_KEY = 1111,                    // デルクフ認証キー
        PRISMATIC_HOURGLASS = 1550,             // 煌く砂時計
        GREEN_INSTITUTE_CARD = 2496,            // 魔法学会の緑色のカード
        WINDURST_TRUST_PERMIT = 2497,           // ウィンダスのフェイス使用許可証
        BLUE_INSTITUTE_CARD = 2498,             // 魔法学会の青いカード
        BASTOK_TRUST_PERMIT = 2499,             // バストゥークのフェイス使用許可証
        RED_INSTITUTE_CARD = 2500,              // 魔法学会の赤いカード
        SAN_DORIA_TRUST_PERMIT = 2501,          // サンドリアのフェイス使用許可証
        TEMPLE_KNIGHT_KEY = 2506,               // 侯国騎士団長のカギ
    }

    /// <summary>
    /// アイテムの特殊効果
    /// </summary>
    public enum ItemMod
    {
        NONE = 0,
        DEF = 1,                                // 防
        HP = 2,                                 // HP+
        HPP = 3,                                // HP+%
        CONVMPTOHP = 4,                         // MPをHPに変換
        MP = 5,                                 // MP+
        MPP = 6,                                // MP+%
        CONVHPTOMP = 7,                         // HPをMPに変換
        STR = 8,                                // STR+
        DEX = 9,                                // DEX+
        VIT = 10,                               // VIT+
        AGI = 11,                               // AGI+
        INT = 12,                               // INT+
        MND = 13,                               // MND+
        CHR = 14,                               // CHR+
        WEAKNESS_PCT = 1093, // 衰弱HP/MP減少項、-1 = -1% HP/MP
        CURSE_PCT = 1094, // 呪いHP/MP減少項、-1 = -1% HP/MP
        BASE_HP = 1095, // 基本HPボーナス (メリットポイントのような)
        BASE_MP = 1096, // 基本MPボーナス (メリットポイントのような)
        FOOD_HP = 1130, // 食事HP (これは呪いの後に追加されます)
        FOOD_MP = 1131, // 食事MP (これは呪いの後に追加されます)

        TWOHAND_STR = 218, // STRと同じですが、両手武器を使用しているときのみ有効です (例: 八双)

        // 属性に対する魔法回避
        // これはSDTと繰り返し混同されてきました - 注意してください！
        FIRE_MEVA = 15,                         // 耐火+
        ICE_MEVA = 16,                          // 耐氷+
        WIND_MEVA = 17,                         // 耐風+
        EARTH_MEVA = 18,                        // 耐土+
        THUNDER_MEVA = 19,                      // 耐雷+
        WATER_MEVA = 20,                        // 耐水+
        LIGHT_MEVA = 21,                        // 耐光+
        DARK_MEVA = 22,                         // 耐闇+

        // 属性に対する魔法回避ランク (耐性ランク)
        FIRE_RES_RANK = 192, // 火属性耐性ランク
        ICE_RES_RANK = 193, // 氷属性耐性ランク
        WIND_RES_RANK = 194, // 風属性耐性ランク
        EARTH_RES_RANK = 195, // 土属性耐性ランク
        THUNDER_RES_RANK = 196, // 雷属性耐性ランク
        WATER_RES_RANK = 197, // 水属性耐性ランク
        LIGHT_RES_RANK = 198, // 光属性耐性ランク
        DARK_RES_RANK = 199, // 闇属性耐性ランク

        ATT = 23,                               // 攻+
        RATT = 24,                              // 飛攻+
        ACC = 25,                               // 命中+
        RACC = 26,                              // 飛命+
        TWOHAND_ACC = 219, // ACCと同じですが、両手武器を使用しているときのみ有効です (例: 八双)
        ENMITY = 27,                            // 敵対心+
        ENMITY_LOSS_REDUCTION = 427,
        MATT = 28,                              // 魔攻+
        MDEF = 29,                              // 魔防+
        MACC = 30,                              // 魔命+
        MEVA = 31,                              // 魔回避+
        FIREATT = 32,                           // 火属性魔攻+
        ICEATT = 33,                            // 氷属性魔攻+
        WINDATT = 34,                           // 風属性魔攻+
        EARTHATT = 35,                          // 土属性魔攻+
        THUNDERATT = 36,                        // 雷属性魔攻+
        WATERATT = 37,                          // 水属性魔攻+
        LIGHTATT = 38,                          // 光属性魔攻+
        DARKATT = 39,                           // 闇属性魔攻+
        FIREACC = 40,                           // 火属性魔命+
        ICEACC = 41,                            // 氷属性魔命+
        WINDACC = 42,                           // 風属性魔命+
        EARTHACC = 43,                          // 土属性魔命+
        THUNDERACC = 44,                        // 雷属性魔命+
        WATERACC = 45,                          // 水属性魔命+
        LIGHTACC = 46,                          // 光属性魔命+
        DARKACC = 47,                           // 闇属性魔命+
        WSACC = 48,                             // ウェポンスキルの命中+
        ATTP = 62,
        DEFP = 63,
        COMBAT_SKILLUP_RATE = 64, // スキルアップ戦闘率の%増加
        MAGIC_SKILLUP_RATE = 65, // スキルアップ魔法率の%増加
        RATTP = 66,
        EVA = 68,                               // 回避+
        RDEF = 69,
        REVA = 70,
        MPHEAL = 71,                            // ヒーリングMP+
        HPHEAL = 72,                            // ヒーリングHP
        STORETP = 73,                           // ストアTP+

        // これらはアイテムレベルのスキルではなく、ステータスメニューのスキルです。iLvlの「スキル」はitem_weapon.sqlで発生します
        HTH = 80,
        DAGGER = 81,
        SWORD = 82,
        GSWORD = 83,
        AXE = 84,
        GAXE = 85,
        SCYTHE = 86,
        POLEARM = 87,
        KATANA = 88,
        GKATANA = 89,
        CLUB = 90,
        STAFF = 91,

        RAMPART_DURATION = 92,  // ランパートの持続時間 (秒)
        FLEE_DURATION = 93,  // フリの持続時間 (秒)
        MEDITATE_DURATION = 94,  // 瞑想の持続時間 (秒)
        WARDING_CIRCLE_DURATION = 95,  // ワーディングサークルの持続時間 (秒)
        BOOST_EFFECT = 97,  // ブーストパワー (1/10単位)
        CAMOUFLAGE_DURATION = 98,  // カモフラージュの持続時間 (パーセント)

        // これらはアイテムレベルのスキルではなく、ステータスメニューのスキルです。iLvlの「スキル」はitem_weapon.sqlで発生します
        AUTO_MELEE_SKILL = 101,
        AUTO_RANGED_SKILL = 102,
        AUTO_MAGIC_SKILL = 103,
        ARCHERY = 104,
        MARKSMAN = 105,
        THROW = 106,                            // 投てきスキル+
        GUARD = 107,                            // ガードスキル+
        EVASION = 108,
        SHIELD = 109,                           // 盾スキル+
        PARRY = 110,                            // 受け流しスキル+

        // 魔法スキル修飾子
        DIVINE = 111,                           // 神聖魔法スキル+
        HEALING = 112,                          // 回復魔法スキル+
        ENHANCE = 113,                          // 強化魔法スキル+
        ENFEEBLE = 114,                         // 弱体魔法スキル+
        ELEM = 115,                             // 精霊魔法スキル+
        DARK = 116,                             // 暗黒魔法スキル+
        SUMMONING = 117,                        // 召喚魔法スキル+
        NINJUTSU = 118,                         // 忍術スキル+
        SINGING = 119,                          // 歌唱スキル+
        STRING = 120,                           // 弦楽器スキル+
        WIND = 121,                             // 管楽器スキル+
        BLUE = 122,                             // 青魔法スキル+
        GEOMANCY_SKILL = 123,
        HANDBELL_SKILL = 124,

        CHAKRA_MULT = 1026, // チャクラの倍率増加
        CHAKRA_REMOVAL = 1027, // チャクラによって除去される追加ステータス
        SUPPRESS_OVERLOAD = 125, // ケンコンケン「オーバーロード抑制」mod。これがどのように機能するかは正確には不明です。リテールでのテストが必要です。
        BP_DAMAGE = 126,                        // 契約の履行ダメージ+
        FISH = 127,                             // 釣りスキル+
        WOOD = 128,
        SMITH = 129,
        GOLDSMITH = 130,
        CLOTH = 131,
        LEATHER = 132,
        BONE = 133,
        ALCHEMY = 134,
        COOK = 135,                             // 調理スキル+
        SYNERGY = 136,
        RIDING = 137,

        // 被ダメージ修飾子。すべてのダメージ修飾子は基本10000なので、375 = 3.75% です。リテールが基本256を使用していることは承知しています。
        DMG = 160,                              // 被ダメージ+%
        DMGPHYS = 161,                          // 被物理ダメージ+%
        DMGPHYS_II = 190, // 物理被ダメージII % (バートガング)。以前のキャップをバイパスします。
        UDMGPHYS = 387, // キャップなし。
        DMGBREATH = 162,                        // 被ブレスダメージ+%
        UDMGBREATH = 388, // キャップなし。
        DMGMAGIC = 163,                         // 被魔法ダメージ+%
        DMGMAGIC_II = 831, // 魔法被ダメージII % (イージス)。以前のキャップをバイパスします。
        UDMGMAGIC = 389, // キャップなし。
        DMGRANGE = 164, // 遠隔被ダメージを修正します。50%でキャップ
        UDMGRANGE = 390, // キャップなし。
        DMG_AOE = 158, // Mobのみ。範囲攻撃アクションの主ターゲットでない場合の被ダメージ%。(例: ローカスMob)。キャップなし。
        RECEIVED_DAMAGE_CAP = 221, // 攻撃者が受ける被ダメージをキャップします
        RECEIVED_DAMAGE_VARIANT = 222, // ダメージキャップを変更したい変動幅。例: ダメージを固定の100ではなく90-100にしたい場合、これを10に設定できます。ダメージが100を超える場合、90-100の間で値をランダム化します。
        SLASH_SDT = 49, // mob_resistances.sqlを上書きします。基本10000ではありません。TODO: 他のすべてと同じように機能するように変更します。
        PIERCE_SDT = 50, // mob_resistances.sqlを上書きします。基本10000ではありません。TODO: 他のすべてと同じように機能するように変更します。
        IMPACT_SDT = 51, // mob_resistances.sqlを上書きします。基本10000ではありません。TODO: 他のすべてと同じように機能するように変更します。
        HTH_SDT = 52, // mob_resistances.sqlを上書きします。基本10000ではありません。TODO: 他のすべてと同じように機能するように変更します。
        FIRE_SDT = 54, // mob_resistances.sqlを上書きします。
        ICE_SDT = 55, // mob_resistances.sqlを上書きします。
        WIND_SDT = 56, // mob_resistances.sqlを上書きします。
        EARTH_SDT = 57, // mob_resistances.sqlを上書きします。
        THUNDER_SDT = 58, // mob_resistances.sqlを上書きします。
        WATER_SDT = 59, // mob_resistances.sqlを上書きします。
        LIGHT_SDT = 60, // mob_resistances.sqlを上書きします。
        DARK_SDT = 61, // mob_resistances.sqlを上書きします。

        // 時々被ダメージを無効にします。修飾子の値 = 確率 (%)
        NULL_DAMAGE = 142, // 時々すべて/任意のダメージを無効にします。
        NULL_PHYSICAL_DAMAGE = 416, // 時々物理ダメージを無効にします。
        NULL_BREATH_DAMAGE = 143, // 時々ブレスダメージを無効にします。
        NULL_MAGICAL_DAMAGE = 476, // 時々魔法ダメージを無効にします。
        NULL_RANGED_DAMAGE = 239, // 時々遠隔ダメージを無効にします。
        FIRE_NULL = 467, // 時々火属性ダメージを無効にします。
        ICE_NULL = 468, // 時々氷属性ダメージを無効にします。
        WIND_NULL = 469, // 時々風属性ダメージを無効にします。
        EARTH_NULL = 470, // 時々土属性ダメージを無効にします。
        LTNG_NULL = 471, // 時々雷属性ダメージを無効にします。
        WATER_NULL = 472, // 時々水属性ダメージを無効にします。
        LIGHT_NULL = 473, // 時々光属性ダメージを無効にします。
        DARK_NULL = 474, // 時々闇属性ダメージを無効にします。

        // 時々被ダメージを吸収します。修飾子の値 = 確率 (%)
        ABSORB_DMG_CHANCE = 480, // 時々すべて/任意のダメージを吸収します。
        PHYS_ABSORB = 512, // 時々物理ダメージを吸収します。遠隔にも使用されます。
        MAGIC_ABSORB = 475, // 時々魔法ダメージを吸収します。
        FIRE_ABSORB = 459, // 時々火属性ダメージを吸収します。
        ICE_ABSORB = 460, // 時々氷属性ダメージを吸収します。
        WIND_ABSORB = 461, // 時々風属性ダメージを吸収します。
        EARTH_ABSORB = 462, // 時々土属性ダメージを吸収します。
        LTNG_ABSORB = 463, // 時々雷属性ダメージを吸収します。
        WATER_ABSORB = 464, // 時々水属性ダメージを吸収します。
        LIGHT_ABSORB = 465, // 時々光属性ダメージを吸収します。
        DARK_ABSORB = 466, // 時々闇属性ダメージを吸収します。

        CRITHITRATE = 165,                      // クリティカルヒット+%
        CRITHITRATE_ONLY_WEP = 141,
        CRIT_DMG_INCREASE = 421,                // クリティカルヒットダメージアップ
        RANGED_CRIT_DMG_INCREASE = 964, // 遠隔クリティカルダメージをパーセントで増加させます
        CRITICAL_HIT_EVASION = 166,             // 被クリティカルヒット-%
        CRIT_DEF_BONUS = 908, // クリティカルヒットダメージを軽減します
        MAGIC_CRITHITRATE = 562,
        MAGIC_CRIT_DMG_INCREASE = 563,
        HASTE_MAGIC = 167,
        SPELLINTERRUPT = 168,                   // 詠唱中断率%ダウン

        // 使用順序での移動速度修飾子。
        MOUNT_MOVE = 972, // % マウント移動速度
        MOVE_SPEED_STACKABLE = 75,              // 移動速度ダウン
        MOVE_SPEED_WEIGHT_PENALTY = 77, // 乗算修飾子。グラビティと呪い用。
        MOVE_SPEED_FLEE = 1085, // 乗算修飾子。
        MOVE_SPEED_CHEER = 1087, // 「応援」タイプのKIからの乗算修飾子。
        MOVE_SPEED_GEAR_BONUS = 76,             // 移動速度+%
        MOVE_SPEED_QUICKENING = 78, // 加算修飾子。乗算の後に適用されます。ジグ、スプリンターシューズなど。マズルカとキャップを共有します。
        MOVE_SPEED_MAZURKA = 79, // 加算修飾子。乗算の後に適用されます。歌の移動速度。クイックニングとキャップを共有します。
        MOVE_SPEED_BOLTERS_ROLL = 1086, // 加算修飾子。乗算の後に適用されます。
        MOVE_SPEED_OVERRIDE = 169, // 通常の速度キャップを上書きするために使用される修飾子。(GMスピードと剣の饗宴)

        FASTCAST = 170,                         // ファストキャスト効果アップ
        UFASTCAST = 407,
        CURE_CAST_TIME = 519,                   // ケアル詠唱時間-%
        ELEMENTAL_CELERITY = 901, // エレメンタル魔法の詠唱を速めます
        DELAY = 171,                            // 隔
        RANGED_DELAY = 172,
        MARTIAL_ARTS = 173,                     // マーシャルアーツ+
        SKILLCHAINBONUS = 174,
        SKILLCHAINDMG = 175,
        MAX_SWINGS = 978,
        ADDITIONAL_SWING_CHANCE = 979,
        FOOD_HPP = 176,
        FOOD_HP_CAP = 177,
        FOOD_MPP = 178,
        FOOD_MP_CAP = 179,
        FOOD_ATTP = 180,
        FOOD_ATT_CAP = 181,
        FOOD_DEFP = 182,
        FOOD_DEF_CAP = 183,
        FOOD_ACCP = 184,
        FOOD_ACC_CAP = 185,
        FOOD_RATTP = 186,
        FOOD_RATT_CAP = 187,
        FOOD_RACCP = 188,
        FOOD_RACC_CAP = 189,
        FOOD_MACCP = 99,
        FOOD_MACC_CAP = 100,
        FOOD_DURATION = 937, // 食事の持続時間を増加させるパーセンテージ
        VERMIN_KILLER = 224,                    // ヴァーミンキラー効果
        BIRD_KILLER = 225,                      // バードキラー効果
        AMORPH_KILLER = 226,                    // アモルフキラー効果
        LIZARD_KILLER = 227,                    // リザードキラー効果
        AQUAN_KILLER = 228,                     // アクアンキラー効果
        PLANTOID_KILLER = 229,                  // プラントイドキラー効果
        BEAST_KILLER = 230,                     // ビーストキラー効果
        UNDEAD_KILLER = 231,                    // アンデッドキラー効果
        ARCANA_KILLER = 232,                    // アルカナキラー効果
        DRAGON_KILLER = 233,                    // ドラゴンキラー効果
        DEMON_KILLER = 234,                     // デーモンキラー効果
        EMPTY_KILLER = 235,                     // エンプティキラー効果
        HUMANOID_KILLER = 236,                  // ヒューマンキラー効果
        LUMINIAN_KILLER = 237,                  // ルミニアンキラー効果
        LUMINION_KILLER = 238,                  // ルミニオンキラー効果

        // ステータス効果 ジョブ特性耐性修飾子。
        SLEEPRES = 240,                         // レジストスリープ効果
        POISONRES = 241,                        // レジストポイズン効果
        PARALYZERES = 242,                      // レジストパライズ効果
        BLINDRES = 243,                         // レジストブライン効果
        SILENCERES = 244,                       // レジストサイレス効果
        VIRUSRES = 245,                         // レジストウィルス効果
        PETRIFYRES = 246,                       // レジストペトリ効果
        BINDRES = 247,
        CURSERES = 248,
        GRAVITYRES = 249,
        SLOWRES = 250,                          // レジストスロウ効果
        STUNRES = 251,
        CHARMRES = 252,
        AMNESIARES = 253,                       // レジストアムネジア効果
        LULLABYRES = 254,
        DEATHRES = 255,
        STATUSRES = 958,                        // 全状態異常のレジスト+

        // ステータス効果 魔法回避修飾子。
        SLEEP_MEVA = 200,
        POISON_MEVA = 201,
        PARALYZE_MEVA = 202,
        BLIND_MEVA = 203,
        SILENCE_MEVA = 204,
        VIRUS_MEVA = 205,
        PETRIFY_MEVA = 206,
        BIND_MEVA = 207,
        CURSE_MEVA = 208,
        GRAVITY_MEVA = 209,
        SLOW_MEVA = 210,
        STUN_MEVA = 211,
        CHARM_MEVA = 212,
        AMNESIA_MEVA = 213,
        LULLABY_MEVA = 214,
        DEATH_MEVA = 215,
        STATUS_MEVA = 216,

        // ステータス効果 魔法回避修飾子。
        SLEEP_IMMUNOBREAK = 261,
        POISON_IMMUNOBREAK = 262,
        PARALYZE_IMMUNOBREAK = 263,
        BLIND_IMMUNOBREAK = 264,
        SILENCE_IMMUNOBREAK = 265,
        PETRIFY_IMMUNOBREAK = 266,
        BIND_IMMUNOBREAK = 267,
        GRAVITY_IMMUNOBREAK = 268,
        SLOW_IMMUNOBREAK = 269,
        ADDLE_IMMUNOBREAK = 270,

        AFTERMATH = 256,
        PARALYZE = 257,
        MIJIN_RERAISE = 258,
        DUAL_WIELD = 259,
        DOUBLE_ATTACK = 288,                    // ダブルアタック+%
        DOUBLE_ATTACK_DMG = 1038, // 「ダブルアタック」ダメージ/「ダブルアタック」ダメージ+ (パーセント単位、例: +20 = +20% ダメージ) を増加させます
        SUBTLE_BLOW = 289,                      // モクシャ+
        SUBTLE_BLOW_II = 973, // サトルブローII効果 (キャップ50%) 合計効果 (SB + SB_II キャップ75%)
        ENF_MAG_POTENCY = 290, // 弱体魔法効果%を増加させます
        COUNTER = 291,                          // カウンター+
        KICK_ATTACK_RATE = 292,                 // 蹴撃+
        AFFLATUS_SOLACE = 293,
        AFFLATUS_MISERY = 294,
        CLEAR_MIND = 295,
        CONSERVE_MP = 296,                      // コンサーブMP+
        ENHANCES_SABOTEUR = 297, // サボトゥール効果%を増加させます
        STEAL = 298,
        DESPOIL = 896,
        PERFECT_DODGE = 883, // パーフェクトドッジの持続時間を秒単位で増加させます
        BLINK = 299,
        STONESKIN = 300,
        PHALANX = 301,
        TRIPLE_ATTACK = 302,
        TRIPLE_ATTACK_DMG = 1039,               // トリプルアタック+%
        TREASURE_HUNTER = 303,
        TREASURE_HUNTER_PROC = 1048, // TODO: トレジャーハンターの発動率を増加させます (パーセント)
        TREASURE_HUNTER_CAP = 1049, // TODO: トレジャーハンターのキャップを増加させます (例: THF JP ギフト)
        TAME = 304,
        RECYCLE = 305,                          // リサイクル+
        ZANSHIN = 306,                          // 残心効果
        UTSUSEMI = 307,
        UTSUSEMI_BONUS = 900, // 装備品からの追加の影
        NINJA_TOOL = 308,
        BLUE_POINTS = 309, // 追加のブルーポイントを追跡します
        BLUE_LEARN_CHANCE = 945, // ブルー魔法を習得する追加のチャンス
        DMG_REFLECT = 316,
        ROLL_ROGUES = 317,
        ROLL_GALLANTS = 318,
        ROLL_CHAOS = 319,
        ROLL_BEAST = 320,
        ROLL_CHORAL = 321,
        ROLL_HUNTERS = 322,
        ROLL_SAMURAI = 323,
        ROLL_NINJA = 324,
        ROLL_DRACHEN = 325,
        ROLL_EVOKERS = 326,
        ROLL_MAGUS = 327,
        ROLL_CORSAIRS = 328,
        ROLL_PUPPET = 329,
        ROLL_DANCERS = 330,
        ROLL_SCHOLARS = 331,
        // コルセアロール レベル65+
        ROLL_BOLTERS = 869,
        ROLL_CASTERS = 870,
        ROLL_COURSERS = 871,
        ROLL_BLITZERS = 872,
        ROLL_TACTICIANS = 873,
        ROLL_ALLIES = 874,
        ROLL_MISERS = 875,
        ROLL_COMPANIONS = 876,
        ROLL_AVENGERS = 877,
        ROLL_NATURALISTS = 878,
        ROLL_RUNEISTS = 879,
        BUST = 332,
        FINISHING_MOVES = 333,
        SAMBA_DURATION = 490, // サンバ持続時間ボーナス
        WALTZ_POTENCY = 491,                    // ワルツ回復量+%
        JIG_DURATION = 492, // ジグ持続時間ボーナス (パーセント)
        VFLOURISH_MACC = 493, // ヴァイオレントフラリッシュ命中ボーナス
        STEP_FINISH = 494, // ステップからのボーナスフィニッシングムーブ
        STEP_ACCURACY = 403, // ステップの命中ボーナス
        WALTZ_DELAY = 497, // ワルツ アビリティディレイ修飾子 (-1 mod は -1 秒)
        SAMBA_PDURATION = 498, // サンバ パーセント持続時間ボーナス
        WALTZ_COST = 139, // ワルツコストを5TP削減 (1000TPスケール後50)
        WIDESCAN = 340,
        BARRAGE_ACC = 420,
        BARRAGE_COUNT = 138, // バラージショットを1増加させます
        ENSPELL = 341, // 有効なエンチャントの種類を保存します (何もない場合は0)
        SPIKES = 342,
        ENSPELL_DMG = 343,
        ENSPELL_CHANCE = 856,
        SPIKES_DMG = 344,
        TP_BONUS = 345,
        PERPETUATION_REDUCTION = 346,           // 召喚獣維持費-
        SPIKES_DMG_BONUS = 1079, // ブレイズ/アイス/ショックスパイクのダメージをパーセンテージで増加させます (例: mod値50 = +50% スパイクダメージ)

        // 戦士
        BERSERK_POTENCY = 948,  // 「バーサク」を増強/「バーサク」効果を強化 (コンカラー)
        BERSERK_DURATION = 954,  // バーサク持続時間
        AGGRESSOR_DURATION = 955,  // アグレッサー持続時間
        DEFENDER_DURATION = 956,  // ディフェンダー持続時間
        ENHANCES_RESTRAINT = 1045, // 「リストレイント」効果を強化/「リストレイント」+ (リストレイントのダメージボーナスをXXX%増加させます)
        ENHANCES_BLOOD_RAGE = 1046, // 「ブラッドレイジ」効果を強化/「ブラッドレイジ」持続時間+

        // モンク
        ADDITIVE_GUARD = 1092, // 最終ガード率への加算%ボーナス (クランプ後に追加)
        AUGMENTS_IMPETUS = 1097, // https://www.bg-wiki.com/ffxi/Impetus を参照してください。インピタスのクリティカルヒットダメージと命中を追加します

        // パラディン
        ENHANCES_CHIVALRY = 1061, // 「シバルリー」効果を強化 (基本TP修飾子を提供された値/100で増加させます。例: mod値5 = +0.05)
        ENHANCES_DIVINE_EMBLEM = 1062, // 「ディバインエンブレム」効果を強化/「ディバインエンブレム」+ (アビリティの特別な敵対心ボーナスを提供された値で増加させます)
        ENHANCES_FEALTY = 1063, // 「フィオルティ」効果を強化 (フィオルティの持続時間をフィオルティメリットごとに4秒増加させます)
        ENHANCES_IRON_WILL = 1064, // 「アイアンウィル」効果を強化 (アイアンウィルメリットごとにランパートに+3%ファストキャストを追加します)
        ENHANCES_GUARDIAN = 1065, // 「ガーディアン」効果を強化 (センチネルの持続時間をガーディアンメリットごとに2秒増加させます)
        PALISADE_BLOCK_BONUS = 1066, // パリセードの効果中の基本ブロック率を増加させます (乗算ではなく加算)
        REPRISAL_BLOCK_BONUS = 1067, // リプライザルの効果中のブロック率を増加させます (加算ではなく乗算)
        REPRISAL_SPIKES_BONUS = 1068, // リプライザルスパイクダメージをパーセンテージで増加させます (例: mod値50はスパイクダメージを50%増加させます)
        SHIELD_BARRIER = 1082, // シールド装備中に自身が詠唱するプロテススペルにボーナスを付与します。

        // 暗黒騎士
        ARCANE_CIRCLE_DURATION = 858,  // アルケインサークルの延長時間 (秒)
        ARCANE_CIRCLE_POTENCY = 1069, // アルケインサークル効果の効力を増加させます (例: mod値2 = +2% アルカナキラー)
        SOULEATER_EFFECT = 96,   // ソウルイーターパワー (パーセント)
        SOULEATER_EFFECT_II = 53,   // キャップなしの加算ソウルイーターボーナス (パーセント)、10 = 0.1
        DESPERATE_BLOWS = 906,  // ラストリゾートにアビリティヘイストを追加します
        STALWART_SOUL = 907,  // ソウルイーターからの被ダメージを軽減します
        DREAD_SPIKES_EFFECT = 998,  // ドレッドスパイクの合計HPドレインのパーセント増加
        DARK_MAGIC_CAST = 1071, // 暗黒魔法の詠唱時間をパーセンテージで短縮します (例: mod値-10 = -10% 詠唱時間)
        DARK_MAGIC_DURATION = 1072, // 暗黒魔法スペルの持続時間をパーセンテージで増加させます (例: mod値10 = +10% 持続時間)
        ENHANCES_BLOOD_WEAPON = 1070, // 「ブラッドウェポン」効果を強化 (ブラッドウェポンの持続時間を秒単位で増加させます)
        ENHANCES_DARK_SEAL = 1073, // 「ダークシール」効果を強化 (ダークシール有効中にダークシールメリットごとに暗黒魔法スペルの持続時間を10%増加させます)
        ENHANCES_DIABOLIC_EYE = 275,  // ディアボリックアイ持続時間 + ディアボリックアイメリットごとに「修飾子値」秒。
        ENHANCES_NETHER_VOID = 1083, // 「ネザーヴォイド」効果を強化 (次のアブゾーブまたはドレイン暗黒魔法の効力を<値>%増加させます
        ENHANCES_MUTED_SOUL = 1084, // 「ミューテッドソウル」効果を強化 (MUTED_SOULメリットレベルごとに斬心率を3%追加します)

        // 獣使い
        TANDEM_STRIKE_POWER = 271,  // あなたとあなたのペットが同じターゲットを攻撃しているときに、あなたとあなたのペットの命中と魔法命中にボーナスを付与します。
        TANDEM_BLOW_POWER = 272,  // あなた

        // サムライ
        SENGIKORI_SC_DMG_DEBUFF = 1088, // 連携ダメージへの%増加。防御側に適用されます。
        SENGIKORI_MB_DMG_DEBUFF = 1089, // 魔法ダメージへの%増加。防御側に適用されます。
        SENGIKORI_BONUS = 1090, // 閃ikoriへの加算%増加

        // 忍者
        ENHANCES_SANGE = 1091, // 1 = 三華中の打剣の攻撃力を三華メリットごとに+1します (つまり、メリット5で20の場合は三華中に+100の攻撃力)

        // 竜騎士
        WYVERN_LVL_BONUS = 1043,                // 飛竜:Lv+

        // 召喚士
        AVATAR_LVL_BONUS = 1040, // 召喚獣: Lv. ###/+ (すべての召喚獣の基本レベルを99以上に増加させます)
        CARBUNCLE_LVL_BONUS = 1041, // カーバンクル: Lv.+ (カーバンクルの基本レベルを99以上に増加させます)
        CAIT_SITH_LVL_BONUS = 1042, // ケート・シー: Lv.+ (ケート・シーの基本レベルを99以上に増加させます)
        ENHANCES_MANA_CEDE = 74,   // マナシード効果へのボーナス%、+1 = 1%
        SUMMONING_MAGIC_CAST = 1078, // 召喚魔法の詠唱時間短縮 (秒)
        SPIRIT_CAST_REDUCTION = 140,  // スピリットパクトの詠唱時間短縮 (秒)

        // からくり士
        AUTOMATON_LVL_BONUS = 1044,             // オートマトン: Lv

        // 風水士
        FULL_CIRCLE = 1025, // フルサークルで返還されるMPの初期倍率を増加させます
        BOLSTER_EFFECT = 1028, // ボーナス持続時間を+N秒として追加します
        LIFE_CYCLE_EFFECT = 1029, // ライフサイクル使用時にルオパンに返還されるHP%にボーナスを追加します
        AURA_SIZE = 1030, // オーラサイズを拡張するために使用されます。計算式は6.25 + (PEntity->getMod(Mod::AURA_SIZE) / 100) なので、100を追加すると7.25になります

        // 魔導剣士
        ENHANCES_BATTUTA = 1004, // RUNメリットポイントカテゴリ2で使用され、バッタータ効果中のパリー スパイクに+N%のボーナスダメージを追加します
        ENHANCES_ELEMENTAL_SFORZO = 1005, // ボーナス持続時間
        ENHANCES_SLEIGHT_OF_SWORD = 1006, // RUNメリットポイントカテゴリ2で使用され、ソードプレイに+N サトルブローを追加します
        ENHANCES_INSPIRATION = 1007, // RUNメリットポイントカテゴリ2で使用され、ヴァリエーション/ヴァリエンスに+N ファストキャストを追加します
        SWORDPLAY = 1008, // ソードプレイにボーナス開始ティックを追加します
        LIEMENT = 1009, // ボーナス持続時間を+N秒として追加します
        VALIANCE_VALLATION_DURATION = 1010, // ボーナス持続時間を+N秒として追加します
        PFLUG = 1011, // +N%でフラットな追加の全耐性率を追加します
        VIVACIOUS_PULSE_POTENCY = 1012, // ビベイシャスパルスの計算に最終HPボーナス+N%を追加します
        AUGMENTS_VIVACIOUS_PULSE = 1013, // ビベイシャスパルスにランダムな消去/-naを追加します
        RAYKE_DURATION = 1014, // ボーナス持続時間を+N秒として追加します
        ODYLLIC_SUBTERFUGE_DURATION = 1015, // ボーナス持続時間を+N秒として追加します
        SWIPE = 1016, // スワイプ/ランジの魔法ダメージ計算にボーナスダメージを追加します
        LIEMENT_DURATION = 1017, // ボーナス持続時間を+N秒として追加します
        GAMBIT_DURATION = 1018, // ボーナス持続時間を+N秒として追加します
        EMBOLDEN_DURATION = 1019, // ボーナス持続時間を+N秒として追加します
        LIEMENT_EXTENDS_TO_AREA = 1020, // エピオラトリー(RUNエルゴン武器)の特殊効果、ライエメントを自身ターゲットのみではなくパーティへの範囲にします。
        INSPIRATION_FAST_CAST = 1021, // インスピレーションのファストキャスト、通常のファストキャストに加算され、80%を超えるキャップがあります
        PARRY_SPIKES = 1022, // バッタータ パリースパイク率
        PARRY_SPIKES_DMG = 1023, // バッタータ パリースパイクダメージ
        SPECIAL_ATTACK_EVASION = 1024, // フォイル「特殊攻撃」回避
        AUGMENTS_SLEIGHT_OF_SWORD = 277,  // メリットごとのボーナス「サトルブロー」を強化します。

        FIRE_AFFINITY_DMG = 347,                // 火属性魔法ダメージ+%
        ICE_AFFINITY_DMG = 348,                 // 氷属性魔法ダメージ+%
        WIND_AFFINITY_DMG = 349,                // 風属性魔法ダメージ+%
        EARTH_AFFINITY_DMG = 350,               // 土属性魔法ダメージ+%
        THUNDER_AFFINITY_DMG = 351,             // 雷属性魔法ダメージ+%
        WATER_AFFINITY_DMG = 352,               // 水属性魔法ダメージ+%
        LIGHT_AFFINITY_DMG = 353,               // 光属性魔法ダメージ+%
        DARK_AFFINITY_DMG = 354,                // 闇属性魔法ダメージ+%

        FIRE_AFFINITY_ACC = 544,                // 火属性魔法命中率+%
        ICE_AFFINITY_ACC = 545,                 // 氷属性魔法命中率+%
        WIND_AFFINITY_ACC = 546,                // 風属性魔法命中率+%
        EARTH_AFFINITY_ACC = 547,               // 土属性魔法命中率+%
        THUNDER_AFFINITY_ACC = 548,             // 雷属性魔法命中率+%
        WATER_AFFINITY_ACC = 549,               // 水属性魔法命中率+%
        LIGHT_AFFINITY_ACC = 550,               // 光属性魔法命中率+%
        DARK_AFFINITY_ACC = 551,                // 闇属性魔法命中率+%

        FIRE_AFFINITY_PERP = 553,               // 火属性召喚獣維持費-
        ICE_AFFINITY_PERP = 554,                // 氷属性召喚獣維持費-
        WIND_AFFINITY_PERP = 555,               // 風属性召喚獣維持費-
        EARTH_AFFINITY_PERP = 556,              // 土属性召喚獣維持費-
        THUNDER_AFFINITY_PERP = 557,            // 雷属性召喚獣維持費-
        WATER_AFFINITY_PERP = 558,              // 水属性召喚獣維持費-
        LIGHT_AFFINITY_PERP = 559,              // 光属性召喚獣維持費-
        DARK_AFFINITY_PERP = 560,               // 闇属性召喚獣維持費-

        ADDS_WEAPONSKILL = 355,                 // 追加WS
        ADDS_WEAPONSKILL_DYN = 356,
        BP_DELAY = 357,                         // 契約の履行使用間隔-
        STEALTH = 358,
        RAPID_SHOT = 359,
        CHARM_TIME = 360,
        JUMP_TP_BONUS = 361,                    // ジャンプ時TPボーナス
        JUMP_SPIRIT_TP_BONUS = 285, // スピリットジャンプのみでジャンプ使用時にプレイヤーが受け取るボーナスTP
        JUMP_ATT_BONUS = 362, // すべてのジャンプのATT%ボーナス
        JUMP_SOUL_SPIRIT_ATT_BONUS = 286, // ソウル&スピリットジャンプのみのATT%ボーナス
        JUMP_ACC_BONUS = 936, // すべてのジャンプの命中ボーナス
        JUMP_DOUBLE_ATTACK = 888, // すべてのジャンプのDA%ボーナス
        HIGH_JUMP_ENMITY_REDUCTION = 363, // ハイジャンプからより多くの敵対心を減らす装備用
        ENHANCES_STRAFE = 282, // ストレイフ メリット オーグメント、ブレス使用時にメリットレベルごとに+50 TP獲得。
        ENHANCES_SPIRIT_LINK = 281, // スピリットリンクに消去/-naを追加します
        REWARD_HP_BONUS = 364,                  // いたわる効果アップ
        SNAP_SHOT = 365,                        // スナップショット効果アップ

        DMG_RATING = 287, // 武器にダメージレーティングを追加します (+DMG オーグメント、マンイーター/ブラウドルフなどの隠し効果)
        MAIN_DMG_RATING = 366,                  // メインウェポン:Ｄ
        SUB_DMG_RATING = 367, // オフハンド武器にダメージレーティングを追加します
        RANGED_DMG_RATING = 376, // 遠隔武器にダメージレーティングを追加します
        MAIN_DMG_RANK = 377, // メイン武器に武器ランクを追加します http://wiki.bluegartr.com/bg/Weapon_Rank
        SUB_DMG_RANK = 378, // サブ武器に武器ランクを追加します
        RANGED_DMG_RANK = 379, // 遠隔武器に武器ランクを追加します

        REGAIN = 368,
        REFRESH = 369,                          // リフレシュ
        REGEN = 370,                            // リジェネ
        AVATAR_PERPETUATION = 371,
        WEATHER_REDUCTION = 372,
        DAY_REDUCTION = 373,
        CURE_POTENCY = 374,                     // ケアル回復量+%
        CURE_POTENCY_II = 260, // % ケアル効果II | 装備からのボーナスは30でキャップされます
        CURE_POTENCY_RCVD = 375,                // 被ケアル回復量+%
        CURE_POTENCY_BONUS = 1051, // TODO: ケアル呪文で回復する量を増加させます (固定量)
        DELAYP = 380,
        RANGED_DELAYP = 381,
        EXP_BONUS = 382,
        HASTE_ABILITY = 383,
        HASTE_GEAR = 384,                       // ヘイスト+%
        TWOHAND_HASTE_ABILITY = 217, // 両手武器使用時の通常攻撃にのみ適用され、HASTE_ABILITYに加算されます
        SHIELD_BASH = 385,
        KICK_DMG = 386,                         // 蹴撃攻撃力アップ
        CHARM_CHANCE = 391,                     // あやつる効果アップ
        WEAPON_BASH = 392,                      // ウェポンバッシュ+
        BLACK_MAGIC_COST = 393,
        WHITE_MAGIC_COST = 394,
        BLACK_MAGIC_CAST = 395,
        WHITE_MAGIC_CAST = 396,
        BLACK_MAGIC_RECAST = 397,
        WHITE_MAGIC_RECAST = 398,
        ALACRITY_CELERITY_EFFECT = 399,
        LIGHT_ARTS_EFFECT = 334,
        DARK_ARTS_EFFECT = 335,
        LIGHT_ARTS_SKILL = 336,
        DARK_ARTS_SKILL = 337,
        LIGHT_ARTS_REGEN = 338, // 光の芸術とタブラ・ラーサからのリジェネボーナスHP
        REGEN_DURATION = 339,
        HELIX_EFFECT = 478,
        HELIX_DURATION = 477,
        STORMSURGE_EFFECT = 400,
        SUBLIMATION_BONUS = 401,
        GRIMOIRE_SPELLCASTING = 489, // 「グリモア: 詠唱時間を短縮」ボーナス
        WYVERN_BREATH = 402,
        UNCAPPED_WYVERN_BREATH = 284, // キャップなしのワイバーンブレスブースト。オーグメントのリテールで使用されます。通常の装備はWYVERN_BREATHを使用する必要があります。
        REGEN_DOWN = 404, // ポイズン
        REFRESH_DOWN = 405, // ペスト、MP減少
        REGAIN_DOWN = 406, // ペスト、TP減少
        MAGIC_DAMAGE = 311,                     // 魔法ダメージ+

        // 装備セット修飾子
        DA_DOUBLE_DMG_RATE = 408,  // ダブルアタックのダブルダメージ確率 %。
        TA_TRIPLE_DMG_RATE = 409,  // トリプルアタックのトリプルダメージ確率 %。
        ZANSHIN_DOUBLE_DAMAGE = 410,  // 斬心のダブルダメージ確率 %。
        RAPID_SHOT_DOUBLE_DAMAGE = 479,  // ラピッドショットのダブルダメージ確率 %。
        EXTRA_DUAL_WIELD_ATTACK = 481,  // 二刀流時に追加攻撃を行う確率
        EXTRA_KICK_ATTACK = 482,  // フットワークを使用せずに攻撃ラウンド中に追加のキックアタックを許可することがあります。
        SAMBA_DOUBLE_DAMAGE = 415,  // サンバアップ時のダブルダメージ確率。
        QUICK_DRAW_TRIPLE_DAMAGE = 417,  // クイックドローでトリプルダメージを与える確率。
        BAR_ELEMENT_NULL_CHANCE = 418,  // バ系エレメンタル呪文は、同じ属性のダメージを無効にすることがあります。
        GRIMOIRE_INSTANT_CAST = 419,  // 現在の術と一致する呪文は、リキャストなしで即座に詠唱されることがあります。
        COUNTERSTANCE_EFFECT = 543,  // カウンタースタンス効果 (パーセント)
        DODGE_EFFECT = 552,  // 回避効果 (パーセント)
        FOCUS_EFFECT = 561,  // フォーカス効果 (パーセント)
        MUG_EFFECT = 835,  // マグ効果 (乗数)
        ACC_COLLAB_EFFECT = 884,  // 転送される敵対心の量を増加させます
        HIDE_DURATION = 885,  // ハイド持続時間増加 (パーセントベース
        GILFINDER = 897,  // ギル%増加
        REVERSE_FLOURISH_EFFECT = 836,  // リバースフローリッシュ効果 (二乗項乗数の1/10)
        SENTINEL_EFFECT = 837,  // センチネル効果 (パーセント)
        REGEN_MULTIPLIER = 838,  // リジェネ基本乗数
        AUGMENT_SONG_STAT = 1003, // 歌の属性に基づくステータスMOD値

        DOUBLE_SHOT_RATE = 422, // ダブルショットが発動する確率
        VELOCITY_SNAPSHOT_BONUS = 423, // ベロシティショット中にスナップショットを増加させます。
        VELOCITY_RATT_BONUS = 424, // ベロシティショット中に遠隔攻撃を増加させます。
        SHADOW_BIND_EXT = 425, // シャドウバインドの時間を延長します
        ABSORB_PHYSDMG_TO_MP = 426, // 物理被ダメージのパーセンテージをMPに吸収します。
        SHIELD_MASTERY_TP = 485, // シールドでブロックしたときのシールドマスタリーTPボーナス
        PERFECT_COUNTER_ATT = 428, // パーフェクトカウンターの効果中にカウンター時に武器ダメージを20増加させます。これは武器ランクにも影響します (ただし、素手で戦う場合は影響しません)。
        FOOTWORK_ATT_BONUS = 429, // フットワークの攻撃ボーナスを増加させます。(タントラゲートル+2は100/1024を152/1024に増加させます)

        MINNE_EFFECT = 433,                     // ミンネ+
        MINUET_EFFECT = 434,                    // メヌエット+
        PAEON_EFFECT = 435,                     // ピーアン+
        REQUIEM_EFFECT = 436,                   // レクイエム+
        THRENODY_EFFECT = 437,                  // スレノディ+
        MADRIGAL_EFFECT = 438,                  // マドリガル+
        MAMBO_EFFECT = 439,                     // マンボ+
        LULLABY_EFFECT = 440,                   // ララバイ+
        ETUDE_EFFECT = 441,                     // エチュード+
        BALLAD_EFFECT = 442,                    // バラード+
        MARCH_EFFECT = 443,                     // マーチ+
        FINALE_EFFECT = 444,                    // フィナーレ+
        CAROL_EFFECT = 445,                     // カロル+
        MAZURKA_EFFECT = 446,                   // マズルカ+
        ELEGY_EFFECT = 447,                     // エナジー+
        PRELUDE_EFFECT = 448,                   // プレリュード+
        HYMNUS_EFFECT = 449,                    // ヒムヌス+
        VIRELAI_EFFECT = 450,                   // ヴィルレー+
        SCHERZO_EFFECT = 451,                   // スケルツォ+
        ALL_SONGS_EFFECT = 452,                 // 全歌+
        MAXIMUM_SONGS_BONUS = 453, //
        SONG_DURATION_BONUS = 454, //
        SONG_SPELLCASTING_TIME = 455,           // 歌の詠唱時間-%

        AVATARS_FAVOR_ENHANCE = 1154, // 契約の履行+1

        QUICK_DRAW_DMG = 411, //
        QUICK_DRAW_MACC = 191, // クイックドロー魔法命中
        QUAD_ATTACK = 430,                      // クワッドアタック+%

        ENSPELL_DMG_BONUS = 432,

        ABSORB_DMG_TO_MP = 516, // PLD装備modとは異なり、すべてのダメージタイプで機能します (エーテリアルイヤリング)

        WARCRY_DURATION = 483, // 装備からのウォークライ持続時間ボーナス
        AUSPICE_EFFECT = 484, // オーピス サトルブロー ボーナス
        TACTICAL_PARRY = 486, // タクティカルパリー TPボーナス
        INHIBIT_TP = 488, // TP獲得を阻害 (パーセント)

        GOV_CLEARS = 496, // GoVページ完了を追跡します (報酬の4%ボーナス用)。

        // リレイズ (自動リレイズ、ATMAで使用されます)
        RERAISE_I = 456, // リレイズ。
        RERAISE_II = 457, // リレイズII。
        RERAISE_III = 458, // リレイズIII。

        ITEM_ADDEFFECT_LVADJUST = 278,          // 使用するレベル補正係数 (存在する場合)
        ITEM_ADDEFFECT_PLACEHLD = 279, // プレースホルダー、これらをまとめて保持したいと考えており、99%これを使用する予定です
        ITEM_ADDEFFECT_DSTAT = 280,             // ボーナスダメージとして使用する攻撃側修飾子 (mnd、intなど)
        ITEM_ADDEFFECT_TYPE = 431,              //  追加効果:  scripts\globals\additional_effects.luaのprocTypeテーブルを参照してください
        ITEM_SUBEFFECT = 499,                   // スパイクと追加効果のアニメーションID
        ITEM_ADDEFFECT_DMG = 500,               // アイテムの追加効果またはスパイクのダメージ
        ITEM_ADDEFFECT_CHANCE = 501,            // アイテムの追加効果またはスパイクの確率
        ITEM_ADDEFFECT_ELEMENT = 950,           // 耐性のための、追加効果またはスパイクの属性
        ITEM_ADDEFFECT_STATUS = 951,            // 追加効果またはスパイクを介して適用しようとするステータス効果ID
        ITEM_ADDEFFECT_POWER = 952,             // MOD_ITEM_ADDEFFECT_STATUSの効果の基本威力
        ITEM_ADDEFFECT_DURATION = 953,          // MOD_ITEM_ADDEFFECT_STATUSの効果の基本持続時間

        FERAL_HOWL_DURATION = 503, // 強化されたモンスタージャックコート+2着用時にメリットごとに+20%の持続時間
        MANEUVER_BONUS = 504, // マニューバーステータスボーナス
        OVERLOAD_THRESH = 505,                  // オーバーロード確率ダウン+
        BURDEN_DECAY = 847, // ティックごとに削除される負担の量を増加させます
        REPAIR_EFFECT = 853, // オートマトンから#個のステータス効果を削除します
        REPAIR_POTENCY = 854, // 注: %による再生量にのみ影響し、即時回復には影響しません!
        PREVENT_OVERLOAD = 855, // オーバーロードは、水マニューバがある場合、代わりに水マニューバを消去します (水オーバーロードを除く)
        EXTRA_DMG_CHANCE = 506, // OCC_DO_EXTRA_DMGの発動率。111は11.1%になります
        OCC_DO_EXTRA_DMG = 507, // 「時々通常のx倍のダメージを与える」の乗数。250は2.5倍のダメージになります。

        REM_OCC_DO_DOUBLE_DMG = 863, // 「時々ダブルダメージを与える」を適用するREMアフターマス発動率
        REM_OCC_DO_TRIPLE_DMG = 864, // 「時々トリプルダメージを与える」を適用するREMアフターマス発動率

        REM_OCC_DO_DOUBLE_DMG_RANGED = 867, // 遠隔攻撃固有
        REM_OCC_DO_TRIPLE_DMG_RANGED = 868, // 遠隔攻撃固有

        MYTHIC_OCC_ATT_TWICE = 865, // 「時々2回攻撃する」発動率
        MYTHIC_OCC_ATT_THRICE = 866, // 「時々3回攻撃する」発動率

        APPRECIATE_GYSAHL_GREENS = 156, // ギサールの野菜の食事効果を強化します

        EAT_RAW_FISH = 412, // これがないと、ミスラだけが生魚を食べることができます (アイテムは使用できません)
        EAT_RAW_MEAT = 413, // これがないと、ガルカだけが生肉を食べることができます (アイテムは使用できません)
        DRINK_DISTILLED = 159, // これがないと、蒸留水を消費できません (アイテムは引き続き使用できます)

        EQUIPMENT_ONLY_RACE = 276,              // 種族性別制限

        ENHANCES_CURSNA_RCVD = 67,              // 被カーズナ+
        ENHANCES_CURSNA = 310,                  // カーズナ効果
        ENHANCES_HOLYWATER = 495,               // 聖水効果アップ
        ENHANCES_PROT_SHELL_RCVD = 977,  // プロテスとシェルの効果を強化 (バイナリMOD)
        ENHANCES_PROT_RCVD = 1050, // TODO: プロテス効果を強化 (パーセント)

        RETALIATION = 414, // リタリエーションヒットのダメージを増加させます
        THIRD_EYE_COUNTER_RATE = 508, // サードアイの予想にカウンターを追加し、星眼を使用している場合、カウンター率は15%増加します
        THIRD_EYE_ANTICIPATE_RATE = 839, // 予想率をパーセントで追加します

        CLAMMING_IMPROVED_RESULTS = 509, //
        CLAMMING_REDUCED_INCIDENTS = 510, //
        CHOCOBO_RIDING_TIME = 511,              // チョコボ騎乗時間+
        HARVESTING_RESULT = 513,                // 収穫技術アップ
        LOGGING_RESULT = 514,                   // 伐採技術アップ
        MINING_RESULT = 515,                    // 採掘技術アップ
        EGGHELM = 517, // エッグヘルム (チョコボ掘り)

        SHIELDBLOCKRATE = 518, // シールドブロック率に影響します。パーセントベース
        SCAVENGE_EFFECT = 312, //
        DIA_DOT = 313, // ディアのDoTダメージを増加させます
        SHARPSHOT = 314, // シャープショット命中ボーナス
        ENH_DRAIN_ASPIR = 315, // ドレインとアスピルの%ダメージブースト
        SNEAK_ATK_DEX = 830, // スニークアタックへの%DEXブースト (装備modの場合、ヒット時に装備する必要があります)
        TRICK_ATK_AGI = 520, // トリックアタックへの%AGIブースト (装備modの場合、ヒット時に装備する必要があります)
        NIN_NUKE_BONUS_INNIN = 223, // 印ninからの忍術ダメージ乗数。
        NIN_NUKE_BONUS_GEAR = 522, // 装備からの忍術ダメージ乗数。例: 虎牙鉢巻。
        DAKEN = 911, // 攻撃時に手裏剣を投げる確率
        AMMO_SWING = 523, // バーチューストーン弾薬 (ジャイラー武器) での追撃率。非プレイヤーには何もしません。
        ROLL_RANGE = 528, // CORロールアビリティの追加範囲。
        PHANTOM_ROLL = 881, // ソーティアスリングからのファントムロール+効果。
        PHANTOM_DURATION = 882, // ファントムロール持続時間+。
        PHANTOM_RECAST = 1076, // ファントムロール リキャスト-。

        ENHANCES_REFRESH = 529, // 「リフレシュ強化」は呪文のティック結果に修飾子ごとに+1を追加します。
        NO_SPELL_MP_DEPLETION = 530, // 呪文詠唱時にMPを消費しない%。
        FORCE_FIRE_DWBONUS = 531, // 1に設定すると、火曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_ICE_DWBONUS = 532, // 1に設定すると、氷曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_WIND_DWBONUS = 533, // 1に設定すると、風曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_EARTH_DWBONUS = 534, // 1に設定すると、土曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_LIGHTNING_DWBONUS = 535, // 1に設定すると、雷曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_WATER_DWBONUS = 536, // 1に設定すると、水曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_LIGHT_DWBONUS = 537, // 1に設定すると、光曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        FORCE_DARK_DWBONUS = 538, // 1に設定すると、闇曜日/天候の呪文ボーナス/ペナルティを強制します。合計が1を超えないようにしてください。
        STONESKIN_BONUS_HP = 539, // ストンスキン呪文に付与されるボーナス「HP」。
        ENHANCES_ELEMENTAL_SIPHON = 540, // エレメンタルサイフォンスキルに追加されるボーナス基本MP。
        BP_DELAY_II = 541, // ブラッドパクトディレイ短縮II
        JOB_BONUS_CHANCE = 542, // パーティにジョブがいなくても、CORロールにジョブボーナスを適用する確率。
        DAY_NUKE_BONUS = 565, // 「曜日に影響を受けるエレメンタル魔法」からのボーナスダメージ (ソーサラー トンバン)
        IRIDESCENCE = 566, // イリデッセンス特性 (追加の天候ダメージ/ペナルティ)
        BARSPELL_AMOUNT = 567, // バ系呪文によって付与される追加のエレメンタル耐性
        RANDOM_DEAL_BONUS = 220, // 2つのアビリティをリセットする%確率
        BARSPELL_MDEF_BONUS = 827,              // 属性耐性魔法能力アップ
        RAPTURE_AMOUNT = 568, // ラプチャー効果に追加されるボーナス量
        EBULLIENCE_AMOUNT = 569, // エブリエンス効果に追加されるボーナス量
        WYVERN_EFFECTIVE_BREATH = 829, // ヒーリングブレスをトリガーする閾値を増加させます
        ENHANCE_DEEP_BREATHING = 283, // ヒーリングブレス計算時にディープブリージングボーナスにメリットレベルごとに5/256を追加します
        AQUAVEIL_COUNT = 832, // アクアベールが削除される前に吸収するヒット数を変更します
        SONG_RECAST_DELAY = 833,                // 歌再詠唱間隔-
        ENH_MAGIC_DURATION = 890,               // 強化魔法の効果時間延長
        ENHANCES_COURSERS_ROLL = 891, // クーリエロール ボーナス%確率
        ENHANCES_CASTERS_ROLL = 892, // キャスターズロール ボーナス%確率
        ENHANCES_BLITZERS_ROLL = 893, // ブリッツァーズロール ボーナス%確率
        ENHANCES_ALLIES_ROLL = 894, // アライズロール ボーナス%確率
        ENHANCES_TACTICIANS_ROLL = 895, // タクティシャンズロール ボーナス%確率
        OCCULT_ACUMEN = 902, // エレメンタルまたは暗黒魔法でダメージを与えたときにボーナスTPを付与します

        QUICK_MAGIC = 909, // 呪文が即座に詠唱される確率 (チェインスペルと同様にリキャストも0に短縮します)

        // オートマトンmod
        AUTO_MAB_COEFFICIENT = 157, // オートマトンにMAB乗数を適用します。この値はボーナス%です。
        AUTO_DECISION_DELAY = 842, // オートマトンのグローバルな決定遅延を短縮します
        AUTO_SHIELD_BASH_DELAY = 843, // オートマトンのグローバルなシールドバッシュ遅延を短縮します
        AUTO_MAGIC_DELAY = 844, // オートマトンのグローバルな魔法遅延を短縮します
        AUTO_HEALING_DELAY = 845, // オートマトンのグローバルなヒーリング遅延を短縮します
        AUTO_HEALING_THRESHOLD = 846, // ヒーリングトリガー閾値を増加させます
        AUTO_SHIELD_BASH_SLOW = 848, // シールドバッシュにスロー効果を追加します
        AUTO_TP_EFFICIENCY = 849, // マスターが90%以上のTPの場合、オートマトンは連携を形成するのを待ちます
        AUTO_SCAN_RESISTS = 850, // オートマトンはターゲットの耐性をスキャンします
        AUTO_STEAM_JACKET = 938, // オートマトンは同じタイプの連続攻撃からのダメージを軽減します
        AUTO_STEAM_JACKET_REDUCTION = 939, // スチームジャケットで軽減されるダメージ量
        AUTO_SCHURZEN = 940, // 致命的なダメージを防ぎ、オートマトンを1HPで残し、アースマニューバを消費します
        AUTO_EQUALIZER = 941, // 受けたダメージに応じて被ダメージを軽減します
        AUTO_PERFORMANCE_BOOST = 942, // 他のアタッチメントのパフォーマンスをパーセンテージで向上させます
        AUTO_ANALYZER = 943, // オートマトンは特殊攻撃からのダメージを複数回軽減します
        AUTO_RANGED_DELAY = 1001, // 遠隔攻撃間の時間を短縮します
        AUTO_RANGED_DAMAGEP = 1002, // オートマトンの遠隔武器ダメージを%増加させます

        // ミシックウェポンMod
        AUGMENTS_ABSORB = 521, // リベレーター装備中の直接アブゾーブ呪文増加 (パーセントベース)
        AOE_NA = 524, // 1に設定すると、-na呪文/イレースがディバインベールで常に範囲化されます
        AUGMENTS_CONVERT = 525, // コンバートHPからMPへの比率乗数。値 = MP乗数率。
        AUGMENTS_SA = 526, // スニークアタックにクリティカルアタックボーナスを追加します。パーセントベース。
        AUGMENTS_TA = 527, // トリックアタックにクリティカルアタックボーナスを追加します。パーセントベース。
        AUGMENTS_FEINT = 502, // フェイントはメリットレベルごとにさらに-10回避を与えます
        AUGMENTS_ASSASSINS_CHARGE = 886, // アサシンチャージにメリットレベルごとに+1%クリティカルヒット率を与えます
        AUGMENTS_AMBUSH = 887, // アンブッシュ条件が満たされたときにメリットレベルごとに+1%トリプルアタックを与えます
        AUGMENTS_AURA_STEAL = 889, // メリットレベルごとに2つの効果がディスペルまたはスティールされる確率20%
        AUGMENTS_CONSPIRATOR = 912, // ヘイトリストのトップにいるプレイヤーにコンスピレイターの恩恵を適用します
        JUG_LEVEL_RANGE = 564, // スポーンしたペットのレベル範囲を減少させます。最大2まで。
        FORCE_JUMP_CRIT = 828, // すべてのジャンプでクリティカルヒットを強制します
        QUICK_DRAW_DMG_PERCENT = 834, // QDダメージへのパーセント増加

        // クラフト/合成修飾子
        SYNTH_SUCCESS_RATE = 851, // 分解を除くすべての合成の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_DESYNTHESIS = 916, // 特に分解の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_WOODWORKING = 1098, // 特に木工の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_SMITHING = 1099, // 特に鍛冶の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_GOLDSMITHING = 1100, // 特に彫金の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_CLOTHCRAFT = 1101, // 特に裁縫の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_LEATHERCRAFT = 1102, // 特に革細工の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_BONECRAFT = 1103, // 特に骨細工の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_ALCHEMY = 1104, // 特に錬金術の成功率ボーナス (パーセント)。
        SYNTH_SUCCESS_RATE_COOKING = 1105, // 特に調理の成功率ボーナス (パーセント)。

        SYNTH_SKILL_GAIN = 852, // 合成スキル上昇率

        SYNTH_SPEED_WOODWORKING = 1106, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_SMITHING = 1107, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_GOLDSMITHING = 1108, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_CLOTHCRAFT = 1109, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_LEATHERCRAFT = 1110, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_BONECRAFT = 1111, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_ALCHEMY = 1112, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)
        SYNTH_SPEED_COOKING = 1113, // エスカッション (フェーズ3 & 4)。合成速度へのボーナス (プロセスを高速化します。ミリ秒と仮定)

        SYNTH_ANTI_NQ_WOODWORKING = 1114, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_SMITHING = 1115, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_GOLDSMITHING = 1116, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_CLOTHCRAFT = 1117, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_LEATHERCRAFT = 1118, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_BONECRAFT = 1119, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_ALCHEMY = 1120, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。
        SYNTH_ANTI_NQ_COOKING = 1121, // エスカッション (フェーズ4)「職人の知識」エンチャント。NQ結果を防ぎ、失敗にします。

        SYNTH_ANTI_HQ_WOODWORKING = 144, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_SMITHING = 145, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_GOLDSMITHING = 146, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_CLOTHCRAFT = 147, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_LEATHERCRAFT = 148, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_BONECRAFT = 149, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_ALCHEMY = 150, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。
        SYNTH_ANTI_HQ_COOKING = 151, // クラフトリング。アイテムの説明に記載されていなくても、関連するスキルタイプのHQのみを防ぎます。

        SYNTH_HQ_RATE = 862, // ハイクオリティ成功率 (パーセントではありません)
        SYNTH_HQ_RATE_WOODWORKING = 1122, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_SMITHING = 1123, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_GOLDSMITHING = 1124, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_CLOTHCRAFT = 1125, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_LEATHERCRAFT = 1126, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_BONECRAFT = 1127, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_ALCHEMY = 1128, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。
        SYNTH_HQ_RATE_COOKING = 1129, // 特定のスキルのハイクオリティ成功率 (パーセントではありません)。エスカッションのエンチャントで使用されます。

        SYNTH_MATERIAL_LOSS = 861, // すべての合成の材料損失率 (パーセント)。
        SYNTH_MATERIAL_LOSS_WOODWORKING = 925, // 木工時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_SMITHING = 926, // 鍛冶時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_GOLDSMITHING = 927, // 彫金時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_CLOTHCRAFT = 928, // 裁縫時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_LEATHERCRAFT = 929, // 革細工時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_BONECRAFT = 930, // 骨細工時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_ALCHEMY = 931, // 錬金術時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_COOKING = 932, // 調理時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_FIRE = 917, // 火のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_ICE = 918, // 氷のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_WIND = 919, // 風のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_EARTH = 920, // 土のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_THUNDER = 921, // 雷のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_WATER = 922, // 水のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_LIGHT = 923, // 光のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)
        SYNTH_MATERIAL_LOSS_DARK = 924, // 闇のクリスタル (またはHQバージョン) 使用時の材料損失率 (パーセント)

        // ウェポンスキル修飾子
        WEAPONSKILL_DAMAGE_BASE = 570, // 1つのウェポンスキルに固有: これがどのように使用されるかについては、modifier.hを参照してください
        ALL_WSDMG_ALL_HITS = 840,               // ウェポンスキルのダメージ+3%
        ALL_WSDMG_FIRST_HIT = 841, // 汎用 (すべてのウェポンスキル) ダメージ、最初のヒットのみ。
        WS_NO_DEPLETE = 949, // ウェポンスキルがTPを消費しない%確率。
        INQUARTATA = 963, // 基本パリー率への加算%ボーナス
        WS_STR_BONUS = 980, // str_wscへの%ボーナス。
        WS_DEX_BONUS = 957, // dex_wscへの%ボーナス。
        WS_VIT_BONUS = 981, // vit_wscへの%ボーナス。
        WS_AGI_BONUS = 982, // agi_wscへの%ボーナス。
        WS_INT_BONUS = 983, // int_wscへの%ボーナス。
        WS_MND_BONUS = 984, // mnd_wscへの%ボーナス。
        WS_CHR_BONUS = 985, // chr_wscへの%ボーナス。

        PET_ATK_DEF = 990, // ペットの物理攻撃、遠隔攻撃、物理防御を増加させます
        PET_ACC_EVA = 991, // ペットの物理命中、遠隔命中、回避を増加させます
        PET_MAB_MDB = 992, // ペットの魔法攻撃と魔法防御を増加させます
        PET_MACC_MEVA = 993, // ペットの魔法命中と回避を増加させます
        PET_ATTR_BONUS = 994, // ペットの属性を増加させます
        PET_TP_BONUS = 995, // ペットのTPボーナスを増加させます

        // サークルアビリティ AF/AF+1からの延長時間
        HOLY_CIRCLE_DURATION = 857,
        ANCIENT_CIRCLE_DURATION = 859,

        // その他
        CURE2MP_PERCENT = 860, // 「ケアル」量の%をMPに変換します
        DIVINE_BENISON = 910, // -Na呪文 (イレースを含む) にファストキャストと敵対心減少を追加します。敵対心減少はファストキャスト量の半分です
        SAVETP = 880, // マイザーズロール / ATMA / 葉隠の効果。
        SMITE = 898, // H2Hまたは2H武器での攻撃増加
        TACTICAL_GUARD = 899, // ガード時のTp獲得増加
        GUARD_PERCENT = 976, // ガードパーセント
        COUNTER_DAMAGE = 1047, // TODO: カウンターアタックからのダメージを増加させます (パーセント)
        FENCER_TP_BONUS = 903,                  // フェンサー+
        FENCER_CRITHITRATE = 904,               // フェンサー+
        SHIELD_DEF_BONUS = 905, // シールド防御ボーナス
        SNEAK_DURATION = 946, // 追加の持続時間 (秒)
        INVISIBLE_DURATION = 947, // 追加の持続時間 (秒)
        CARDINAL_CHANT = 959,
        INDI_DURATION = 960,
        GEOMANCY_BONUS = 961,                   // 風水魔法+
        WIDENED_COMPASS = 962,
        MENDING_HALATION = 968, // このmodは1を超えてはなりません。乗数はメリットであり、これは基本的に単なるbool modです
        RADIAL_ARCANA = 969,
        CURATIVE_RECANTATION = 970,
        PRIMEVAL_ZEAL = 971,
        COVER_TO_MP = 965, // 成功したカバーの物理ダメージをMPに変換します
        COVER_MAGIC_AND_RANGED = 966, // 遠隔攻撃と単体魔法攻撃をカバーアビリティ使用者にリダイレクトします
        COVER_DURATION = 967, // カバー持続時間を増加させます
        WYVERN_SUBJOB_TRAITS = 974, // ワイバーンにサブジョブ特性を追加します
        GARDENING_WILT_BONUS = 975, // 植物が枯れる前に生存できるバナデイズの数を増やします
        CALL_BEAST_DELAY = 273, // コールビーストのリキャストを短縮します

        WYVERN_BREATH_MACC = 986,
        REGEN_BONUS = 989,

        SUPERIOR_LEVEL = 997, // SU0..5
        ONE_HOUR_RECAST = 996, // 1時間アビリティのリキャスト時間をn分短縮します。

        PENGUIN_RING_EFFECT = 152, // ミニゲームの釣り矢印遅延 / 魚の動きに+2
        ALBATROSS_RING_EFFECT = 153, // ミニゲーム時間に30秒追加
        PELICAN_RING_EFFECT = 154, // 釣りに追加のスキルアップロールを追加
        FISHING_SKILL_GAIN = 155, // 釣りスキルアップのための食事増加

        BLOOD_BOON = 913, // 時々、ブラッドパクトアビリティのMPコストを削減します。アストラル・フローを必要とするアビリティには影響しません。
        EXPERIENCE_RETAINED = 914, // 死亡時に保持される経験値 (これはパーセンテージです)
        CAPACITY_BONUS = 915,                   // 取得キャパシティポイントボーナス+

        CONQUEST_BONUS = 933, // 付与されるコンクェストポイントボーナス (パーセンテージ)
        CONQUEST_REGION_BONUS = 934, // コンクェストポイントを受け取るときにプレイヤーの国に与えられる影響ポイントを増加させます
        CAMPAIGN_BONUS = 935, // 同盟軍の評価をパーセンテージで増加させます

        CONSERVE_TP = 944, // コンサーブTP特性、10から200 TPの間のランダムな確率

        AUTO_ELEM_CAPACITY = 987, // オートマトンのアタッチメントのエレメンタルキャパシティを増加させます
        MAX_FINISHING_MOVE_BONUS = 988, // 格納できるフィニッシングムーブの最大数を増加させます

        TRIPLE_SHOT_RATE = 999, // トリプルショット率のパーセント増加
        NINJUTSU_DURATION = 1000,

        // AF3セットボーナス修飾子
        AUGMENT_CONSERVE_MP = 1031, // コンサーブMP量に基づいて追加ダメージを与える確率 (BLM AF3セット)
        AUGMENT_COMPOSURE = 1032, // 他の人のためのパーセント強化持続時間延長 (RDM AF3セット)
        AUGMENT_DAMAGE_HP = 1033, // プレイヤーのHP%に基づいてダメージを増加させる確率 (DRK AF3セット)
        AUGMENT_DAMAGE_PET_HP = 1034, // ペットのHP%に基づいてダメージを増加させる確率 (BST/DRG AF3セット)
        AUGMENT_BLOOD_BOON = 1035, // ブラッドブーン量に基づいて追加ダメージを与える確率 (SMN AF3セット)
        AUGMENT_BLU_MAGIC = 1036, // BLU魔法が呪文の3倍のWSC値を受け取る確率 (BLU AF3セット)
        GEOMANCY_MP_NO_DEPLETE = 1037, // ジオマンシーが0 MPを消費する確率 (GEO AF3セット)

        // ジョブポイントギフト
        SIC_READY_RECAST = 1052, // SIC/レディ リキャスト短縮 (秒)
        TRUE_SHOT_EFFECT = 1053, // TODO: トゥルーショット遠隔ダメージ増加 (パーセント)
        DEAD_AIM_EFFECT = 1054, // TODO: デッドエイム クリティカルダメージ増加 (パーセント)
        THIRD_EYE_BONUS = 1055, // TODO: ボーナス サードアイ回避 (カウント)
        WYVERN_ATTRIBUTE_DA = 1056, // ワイバーンの属性が増加するたびに、竜騎士にダブルアタックの量を追加します (パーセント)
        DRAGOON_BREATH_RECAST = 1057, // リストーリング/スミシングブレス リキャスト短縮 (秒)
        BLUE_JOB_TRAIT_BONUS = 1058, // TODO: 装備されたブルー魔法から得られるジョブ特性を増加させます (パーセント)
        BLUE_MAGIC_EFFECT = 1059, // TODO: 呪文の属性値へのボーナス (パーセント)
        QUICK_DRAW_RECAST = 1060, // クイックドロー チャージ短縮 (秒)

        DIG_BYPASS_FATIGUE = 1074, // 「ブルーレースシルク」にあるチョコボ掘り修飾子。修飾子は直接パーセントとして機能します。
        BREATH_DMG_DEALT = 1075, // 与えたブレスダメージ

        STEP_TP_CONSUMED = 1077, // ダンサーステップで消費されるTPの量を変更します

        DAMAGE_LIMIT = 1080, // ダメージリミット増加。一部の特性に見られます。pDIFに追加される固定値です (maxpDIF + DL/100) https://www.bg-wiki.com/ffxi/Damage_Limit%2B
        DAMAGE_LIMITP = 1081, // ダメージリミット+%増加。一部の装備に見られます。固定ダメージリミットの後に追加される乗数です ((maxpDIF + DL/100)*(100 + DLP/100)/100) https://www.ffxiah.com/forum/topic/56649/physical-damage-limit/

        MAGIC_BURST_BONUS_CAPPED = 487,         // マジックバーストダメージボーナス
        MAGIC_BURST_BONUS_UNCAPPED = 274, // 装備、JPギフト、BLM JP、ジョブ特性からのマジックバーストボーナスII。既知のキャップはありません。
    }

    public enum ItemEffect
    {
        EFFECT_KO = 0,
        EFFECT_WEAKNESS = 1,
        EFFECT_SLEEP = 2,                       // 睡眠
        EFFECT_POISON = 3,                      // 毒
        EFFECT_PARALYSIS = 4,                   // 麻痺
        EFFECT_BLINDNESS = 5,                   // 暗闇
        EFFECT_SILENCE = 6,                     // 静寂
        EFFECT_PETRIFICATION = 7,
        EFFECT_DISEASE = 8,
        EFFECT_CURSE = 9,                       // 呪い
        EFFECT_STUN = 10,                       // スタン
        EFFECT_BIND = 11,                       // バインド
        EFFECT_WEIGHT = 12,
        EFFECT_SLOW = 13,
        EFFECT_CHARM = 14,
        EFFECT_DOOM = 15,
        EFFECT_AMNESIA = 16,
        EFFECT_CHARM_II = 17,
        EFFECT_GRADUAL_PETRIFICATION = 18,
        EFFECT_SLEEP_II = 19,                   // デス
        EFFECT_CURSE_II = 20,
        EFFECT_ADDLE = 21,
        EFFECT_INTIMIDATE = 22,
        EFFECT_KAUSTRA = 23,
        EFFECT_TERROR = 28,                     // テラー
        EFFECT_MUTE = 29,
        EFFECT_BANE = 30,
        EFFECT_PLAGUE = 31,
        EFFECT_FLEE = 32,
        EFFECT_HASTE = 33,                      // ヘイスト
        EFFECT_BLAZE_SPIKES = 34,
        EFFECT_ICE_SPIKES = 35,
        EFFECT_BLINK = 36,
        EFFECT_STONESKIN = 37,
        EFFECT_SHOCK_SPIKES = 38,
        EFFECT_AQUAVEIL = 39,
        EFFECT_PROTECT = 40,
        EFFECT_SHELL = 41,
        EFFECT_REGEN = 42,
        EFFECT_REFRESH = 43,
        EFFECT_MIGHTY_STRIKES = 44,
        EFFECT_BOOST = 45,
        EFFECT_HUNDRED_FISTS = 46,
        EFFECT_MANAFONT = 47,
        EFFECT_CHAINSPELL = 48,
        EFFECT_PERFECT_DODGE = 49,
        EFFECT_INVINCIBLE = 50,
        EFFECT_BLOOD_WEAPON = 51,
        EFFECT_SOUL_VOICE = 52,
        EFFECT_EAGLE_EYE_SHOT = 53,
        EFFECT_MEIKYO_SHISUI = 54,
        EFFECT_ASTRAL_FLOW = 55,
        EFFECT_BERSERK = 56,
        EFFECT_DEFENDER = 57,
        EFFECT_AGGRESSOR = 58,
        EFFECT_FOCUS = 59,
        EFFECT_DODGE = 60,
        EFFECT_COUNTERSTANCE = 61,
        EFFECT_SENTINEL = 62,
        EFFECT_SOULEATER = 63,
        EFFECT_LAST_RESORT = 64,
        EFFECT_SNEAK_ATTACK = 65,
        EFFECT_COPY_IMAGE = 66,
        //EFFECT_COPY_IMAGE_1 = 66,
        EFFECT_THIRD_EYE = 67,
        EFFECT_WARCRY = 68,
        EFFECT_INVISIBLE = 69,
        EFFECT_DEODORIZE = 70,
        EFFECT_SNEAK = 71,
        EFFECT_SHARPSHOT = 72,
        EFFECT_BARRAGE = 73,
        EFFECT_HOLY_CIRCLE = 74,
        EFFECT_ARCANE_CIRCLE = 75,
        EFFECT_HIDE = 76,
        EFFECT_CAMOUFLAGE = 77,
        EFFECT_DIVINE_SEAL = 78,
        EFFECT_ELEMENTAL_SEAL = 79,
        EFFECT_STR_BOOST = 80,
        EFFECT_DEX_BOOST = 81,
        EFFECT_VIT_BOOST = 82,
        EFFECT_AGI_BOOST = 83,
        EFFECT_INT_BOOST = 84,
        EFFECT_MND_BOOST = 85,
        EFFECT_CHR_BOOST = 86,
        EFFECT_TRICK_ATTACK = 87,
        EFFECT_MAX_HP_BOOST = 88,
        EFFECT_MAX_MP_BOOST = 89,
        EFFECT_ACCURACY_BOOST = 90,
        EFFECT_ATTACK_BOOST = 91,
        EFFECT_EVASION_BOOST = 92,
        EFFECT_DEFENSE_BOOST = 93,
        EFFECT_ENFIRE = 94,
        EFFECT_ENBLIZZARD = 95,
        EFFECT_ENAERO = 96,
        EFFECT_ENSTONE = 97,
        EFFECT_ENTHUNDER = 98,
        EFFECT_ENWATER = 99,
        EFFECT_BARFIRE = 100,
        EFFECT_BARBLIZZARD = 101,
        EFFECT_BARAERO = 102,
        EFFECT_BARSTONE = 103,
        EFFECT_BARTHUNDER = 104,
        EFFECT_BARWATER = 105,
        EFFECT_BARSLEEP = 106,
        EFFECT_BARPOISON = 107,
        EFFECT_BARPARALYZE = 108,
        EFFECT_BARBLIND = 109,
        EFFECT_BARSILENCE = 110,
        EFFECT_BARPETRIFY = 111,
        EFFECT_BARVIRUS = 112,
        EFFECT_RERAISE = 113,
        EFFECT_COVER = 114,
        EFFECT_UNLIMITED_SHOT = 115,
        EFFECT_PHALANX = 116,
        EFFECT_WARDING_CIRCLE = 117,
        EFFECT_ANCIENT_CIRCLE = 118,
        EFFECT_STR_BOOST_2 = 119,
        EFFECT_DEX_BOOST_2 = 120,
        EFFECT_VIT_BOOST_2 = 121,
        EFFECT_AGI_BOOST_2 = 122,
        EFFECT_INT_BOOST_2 = 123,
        EFFECT_MND_BOOST_2 = 124,
        EFFECT_CHR_BOOST_2 = 125,
        EFFECT_SPIRIT_SURGE = 126,
        EFFECT_COSTUME = 127,
        EFFECT_BURN = 128,
        EFFECT_FROST = 129,
        EFFECT_CHOKE = 130,                     // チョーク
        EFFECT_RASP = 131,
        EFFECT_SHOCK = 132,
        EFFECT_DROWN = 133,
        EFFECT_DIA = 134,
        EFFECT_BIO = 135,
        EFFECT_STR_DOWN = 136,
        EFFECT_DEX_DOWN = 137,
        EFFECT_VIT_DOWN = 138,
        EFFECT_AGI_DOWN = 139,
        EFFECT_INT_DOWN = 140,
        EFFECT_MND_DOWN = 141,
        EFFECT_CHR_DOWN = 142,
        EFFECT_LEVEL_RESTRICTION = 143,
        EFFECT_MAX_HP_DOWN = 144,
        EFFECT_MAX_MP_DOWN = 145,
        EFFECT_ACCURACY_DOWN = 146,
        EFFECT_ATTACK_DOWN = 147,               // 攻撃力ダウン
        EFFECT_EVASION_DOWN = 148,              // 回避率ダウン
        EFFECT_DEFENSE_DOWN = 149,              // 防御力ダウン
        EFFECT_PHYSICAL_SHIELD = 150,
        EFFECT_ARROW_SHIELD = 151,
        EFFECT_MAGIC_SHIELD = 152,
        EFFECT_DAMAGE_SPIKES = 153,
        EFFECT_SHINING_RUBY = 154,
        EFFECT_MEDICINE = 155,                  // フラッシュ
        EFFECT_FLASH = 156,
        EFFECT_SJ_RESTRICTION = 157,
        EFFECT_PROVOKE = 158,
        EFFECT_PENALTY = 159,
        EFFECT_PREPARATIONS = 160,
        EFFECT_SPRINT = 161,
        EFFECT_ENCHANTMENT = 162,
        EFFECT_AZURE_LORE = 163,
        EFFECT_CHAIN_AFFINITY = 164,
        EFFECT_BURST_AFFINITY = 165,
        EFFECT_OVERDRIVE = 166,
        EFFECT_MAGIC_DEF_DOWN = 167,
        EFFECT_INHIBIT_TP = 168,
        EFFECT_POTENCY = 169,
        EFFECT_REGAIN = 170,
        EFFECT_PAX = 171,
        EFFECT_INTENSION = 172,
        EFFECT_DREAD_SPIKES = 173,
        EFFECT_MAGIC_ACC_DOWN = 174,
        EFFECT_MAGIC_ATK_DOWN = 175,
        EFFECT_QUICKENING = 176,
        EFFECT_ENCUMBRANCE_II = 177,
        EFFECT_FIRESTORM = 178,
        EFFECT_HAILSTORM = 179,
        EFFECT_WINDSTORM = 180,
        EFFECT_SANDSTORM = 181,
        EFFECT_THUNDERSTORM = 182,
        EFFECT_RAINSTORM = 183,
        EFFECT_AURORASTORM = 184,
        EFFECT_VOIDSTORM = 185,
        EFFECT_HELIX = 186,
        EFFECT_SUBLIMATION_ACTIVATED = 187,
        EFFECT_SUBLIMATION_COMPLETE = 188,
        EFFECT_MAX_TP_DOWN = 189,
        EFFECT_MAGIC_ATK_BOOST = 190,
        EFFECT_MAGIC_DEF_BOOST = 191,
        EFFECT_REQUIEM = 192,
        EFFECT_LULLABY = 193,
        EFFECT_ELEGY = 194,
        EFFECT_PAEON = 195,
        EFFECT_BALLAD = 196,
        EFFECT_MINNE = 197,
        EFFECT_MINUET = 198,
        EFFECT_MADRIGAL = 199,
        EFFECT_PRELUDE = 200,
        EFFECT_MAMBO = 201,
        EFFECT_AUBADE = 202,
        EFFECT_PASTORAL = 203,
        EFFECT_HUM = 204,
        EFFECT_FANTASIA = 205,
        EFFECT_OPERETTA = 206,
        EFFECT_CAPRICCIO = 207,
        EFFECT_SERENADE = 208,
        EFFECT_ROUND = 209,
        EFFECT_GAVOTTE = 210,
        EFFECT_FUGUE = 211,
        EFFECT_RHAPSODY = 212,
        EFFECT_ARIA = 213,
        EFFECT_MARCH = 214,
        EFFECT_ETUDE = 215,
        EFFECT_CAROL = 216,
        EFFECT_THRENODY = 217,
        EFFECT_HYMNUS = 218,
        EFFECT_MAZURKA = 219,
        EFFECT_SIRVENTE = 220,
        EFFECT_DIRGE = 221,
        EFFECT_SCHERZO = 222,
        EFFECT_NOCTURNE = 223,
        EFFECT_STORE_TP = 227,
        EFFECT_EMBRAVA = 228,
        EFFECT_MANAWELL = 229,
        EFFECT_SPONTANEITY = 230,
        EFFECT_MARCATO = 231,
        EFFECT_NA = 232,
        EFFECT_AUTO_REGEN = 233,
        EFFECT_AUTO_REFRESH = 234,
        EFFECT_FISHING_IMAGERY = 235,
        EFFECT_WOODWORKING_IMAGERY = 236,
        EFFECT_SMITHING_IMAGERY = 237,
        EFFECT_GOLDSMITHING_IMAGERY = 238,
        EFFECT_CLOTHCRAFT_IMAGERY = 239,
        EFFECT_LEATHERCRAFT_IMAGERY = 240,
        EFFECT_BONECRAFT_IMAGERY = 241,
        EFFECT_ALCHEMY_IMAGERY = 242,
        EFFECT_COOKING_IMAGERY = 243,
        EFFECT_IMAGERY_1 = 244,
        EFFECT_IMAGERY_2 = 245,
        EFFECT_IMAGERY_3 = 246,
        EFFECT_IMAGERY_4 = 247,
        EFFECT_IMAGERY_5 = 248,
        EFFECT_DEDICATION = 249,
        EFFECT_EF_BADGE = 250,
        EFFECT_FOOD = 251,
        EFFECT_MOUNTED = 252,
        EFFECT_SIGNET = 253,
        EFFECT_BATTLEFIELD = 254,
        EFFECT_NONE = 255,
        EFFECT_SANCTION = 256,
        EFFECT_BESIEGED = 257,
        EFFECT_ILLUSION = 258,
        EFFECT_ENCUMBRANCE = 259,
        EFFECT_OBLIVISCENCE = 260,
        EFFECT_IMPAIRMENT = 261,
        EFFECT_OMERTA = 262,
        EFFECT_DEBILITATION = 263,
        EFFECT_PATHOS = 264,
        EFFECT_FLURRY = 265,
        EFFECT_CONCENTRATION = 266,
        EFFECT_ALLIED_TAGS = 267,
        EFFECT_SIGIL = 268,
        EFFECT_LEVEL_SYNC = 269,
        EFFECT_AFTERMATH_LV1 = 270,
        EFFECT_AFTERMATH_LV2 = 271,
        EFFECT_AFTERMATH_LV3 = 272,
        EFFECT_AFTERMATH = 273,
        EFFECT_ENLIGHT = 274,
        EFFECT_AUSPICE = 275,
        EFFECT_CONFRONTATION = 276,
        EFFECT_ENFIRE_II = 277,
        EFFECT_ENBLIZZARD_II = 278,
        EFFECT_ENAERO_II = 279,
        EFFECT_ENSTONE_II = 280,
        EFFECT_ENTHUNDER_II = 281,
        EFFECT_ENWATER_II = 282,
        EFFECT_PERFECT_DEFENSE = 283,
        EFFECT_EGG = 284,
        EFFECT_VISITANT = 285,
        EFFECT_BARAMNESIA = 286,
        EFFECT_ATMA = 287,
        EFFECT_ENDARK = 288,
        EFFECT_ENMITY_BOOST = 289,
        EFFECT_SUBTLE_BLOW_PLUS = 290,
        EFFECT_ENMITY_DOWN = 291,
        EFFECT_PENNANT = 292,
        EFFECT_NEGATE_PETRIFY = 293,
        EFFECT_NEGATE_TERROR = 294,
        EFFECT_NEGATE_AMNESIA = 295,
        EFFECT_NEGATE_DOOM = 296,
        EFFECT_NEGATE_POISON = 297,
        EFFECT_CRIT_HIT_EVASION_DOWN = 298,
        EFFECT_OVERLOAD = 299,
        EFFECT_FIRE_MANEUVER = 300,
        EFFECT_ICE_MANEUVER = 301,
        EFFECT_WIND_MANEUVER = 302,
        EFFECT_EARTH_MANEUVER = 303,
        EFFECT_THUNDER_MANEUVER = 304,
        EFFECT_WATER_MANEUVER = 305,
        EFFECT_LIGHT_MANEUVER = 306,
        EFFECT_DARK_MANEUVER = 307,
        EFFECT_DOUBLE_UP_CHANCE = 308,
        EFFECT_BUST = 309,
        EFFECT_FIGHTERS_ROLL = 310,
        EFFECT_MONKS_ROLL = 311,
        EFFECT_HEALERS_ROLL = 312,
        EFFECT_WIZARDS_ROLL = 313,
        EFFECT_WARLOCKS_ROLL = 314,
        EFFECT_ROGUES_ROLL = 315,
        EFFECT_GALLANTS_ROLL = 316,
        EFFECT_CHAOS_ROLL = 317,
        EFFECT_BEAST_ROLL = 318,
        EFFECT_CHORAL_ROLL = 319,
        EFFECT_HUNTERS_ROLL = 320,
        EFFECT_SAMURAI_ROLL = 321,
        EFFECT_NINJA_ROLL = 322,
        EFFECT_DRACHEN_ROLL = 323,
        EFFECT_EVOKERS_ROLL = 324,
        EFFECT_MAGUSS_ROLL = 325,
        EFFECT_CORSAIRS_ROLL = 326,
        EFFECT_PUPPET_ROLL = 327,
        EFFECT_DANCERS_ROLL = 328,
        EFFECT_SCHOLARS_ROLL = 329,
        EFFECT_BOLTERS_ROLL = 330,
        EFFECT_CASTERS_ROLL = 331,
        EFFECT_COURSERS_ROLL = 332,
        EFFECT_BLITZERS_ROLL = 333,
        EFFECT_TACTICIANS_ROLL = 334,
        EFFECT_ALLIES_ROLL = 335,
        EFFECT_MISERS_ROLL = 336,
        EFFECT_COMPANIONS_ROLL = 337,
        EFFECT_AVENGERS_ROLL = 338,
        EFFECT_NATURALISTS_ROLL = 339,
        EFFECT_WARRIORS_CHARGE = 340,
        EFFECT_FORMLESS_STRIKES = 341,
        EFFECT_ASSASSINS_CHARGE = 342,
        EFFECT_FEINT = 343,
        EFFECT_FEALTY = 344,
        EFFECT_DARK_SEAL = 345,
        EFFECT_DIABOLIC_EYE = 346,
        EFFECT_NIGHTINGALE = 347,
        EFFECT_TROUBADOUR = 348,
        EFFECT_KILLER_INSTINCT = 349,
        EFFECT_STEALTH_SHOT = 350,
        EFFECT_FLASHY_SHOT = 351,
        EFFECT_SANGE = 352,
        EFFECT_HASSO = 353,
        EFFECT_SEIGAN = 354,
        EFFECT_CONVERGENCE = 355,
        EFFECT_DIFFUSION = 356,
        EFFECT_SNAKE_EYE = 357,
        EFFECT_LIGHT_ARTS = 358,
        EFFECT_DARK_ARTS = 359,
        EFFECT_PENURY = 360,
        EFFECT_PARSIMONY = 361,
        EFFECT_CELERITY = 362,
        EFFECT_ALACRITY = 363,
        EFFECT_RAPTURE = 364,
        EFFECT_EBULLIENCE = 365,
        EFFECT_ACCESSION = 366,
        EFFECT_MANIFESTATION = 367,
        EFFECT_DRAIN_SAMBA = 368,
        EFFECT_ASPIR_SAMBA = 369,
        EFFECT_HASTE_SAMBA = 370,
        EFFECT_VELOCITY_SHOT = 371,
        EFFECT_BUILDING_FLOURISH = 375,
        EFFECT_TRANCE = 376,
        EFFECT_TABULA_RASA = 377,
        EFFECT_DRAIN_DAZE = 378,
        EFFECT_ASPIR_DAZE = 379,
        EFFECT_HASTE_DAZE = 380,
        EFFECT_FINISHING_MOVE_1 = 381,
        EFFECT_FINISHING_MOVE_2 = 382,
        EFFECT_FINISHING_MOVE_3 = 383,
        EFFECT_FINISHING_MOVE_4 = 384,
        EFFECT_FINISHING_MOVE_5 = 385,
        EFFECT_LETHARGIC_DAZE_1 = 386,
        EFFECT_LETHARGIC_DAZE_2 = 387,
        EFFECT_LETHARGIC_DAZE_3 = 388,
        EFFECT_LETHARGIC_DAZE_4 = 389,
        EFFECT_LETHARGIC_DAZE_5 = 390,
        EFFECT_SLUGGISH_DAZE_1 = 391,
        EFFECT_SLUGGISH_DAZE_2 = 392,
        EFFECT_SLUGGISH_DAZE_3 = 393,
        EFFECT_SLUGGISH_DAZE_4 = 394,
        EFFECT_SLUGGISH_DAZE_5 = 395,
        EFFECT_WEAKENED_DAZE_1 = 396,
        EFFECT_WEAKENED_DAZE_2 = 397,
        EFFECT_WEAKENED_DAZE_3 = 398,
        EFFECT_WEAKENED_DAZE_4 = 399,
        EFFECT_WEAKENED_DAZE_5 = 400,
        EFFECT_ADDENDUM_WHITE = 401,
        EFFECT_ADDENDUM_BLACK = 402,
        EFFECT_REPRISAL = 403,
        EFFECT_MAGIC_EVASION_DOWN = 404,
        EFFECT_RETALIATION = 405,
        EFFECT_FOOTWORK = 406,
        EFFECT_KLIMAFORM = 407,
        EFFECT_SEKKANOKI = 408,
        EFFECT_PIANISSIMO = 409,
        EFFECT_SABER_DANCE = 410,
        EFFECT_FAN_DANCE = 411,
        EFFECT_ALTRUISM = 412,
        EFFECT_FOCALIZATION = 413,
        EFFECT_TRANQUILITY = 414,
        EFFECT_EQUANIMITY = 415,
        EFFECT_ENLIGHTENMENT = 416,
        EFFECT_AFFLATUS_SOLACE = 417,
        EFFECT_AFFLATUS_MISERY = 418,
        EFFECT_COMPOSURE = 419,
        EFFECT_YONIN = 420,
        EFFECT_INNIN = 421,
        EFFECT_CARBUNCLES_FAVOR = 422,
        EFFECT_IFRITS_FAVOR = 423,
        EFFECT_SHIVAS_FAVOR = 424,
        EFFECT_GARUDAS_FAVOR = 425,
        EFFECT_TITANS_FAVOR = 426,
        EFFECT_RAMUHS_FAVOR = 427,
        EFFECT_LEVIATHANS_FAVOR = 428,
        EFFECT_FENRIRS_FAVOR = 429,
        EFFECT_DIABOLOSS_FAVOR = 430,
        EFFECT_AVATARS_FAVOR = 431,
        EFFECT_MULTI_STRIKES = 432,
        EFFECT_DOUBLE_SHOT = 433,
        EFFECT_TRANSCENDENCY = 434,
        EFFECT_RESTRAINT = 435,
        EFFECT_PERFECT_COUNTER = 436,
        EFFECT_MANA_WALL = 437,
        EFFECT_DIVINE_EMBLEM = 438,
        EFFECT_NETHER_VOID = 439,
        EFFECT_SENGIKORI = 440,
        EFFECT_FUTAE = 441,
        EFFECT_PRESTO = 442,
        EFFECT_CLIMACTIC_FLOURISH = 443,
        EFFECT_COPY_IMAGE_2 = 444,
        EFFECT_COPY_IMAGE_3 = 445,
        EFFECT_COPY_IMAGE_4 = 446,
        EFFECT_MULTI_SHOTS = 447,
        EFFECT_BEWILDERED_DAZE_1 = 448,
        EFFECT_BEWILDERED_DAZE_2 = 449,
        EFFECT_BEWILDERED_DAZE_3 = 450,
        EFFECT_BEWILDERED_DAZE_4 = 451,
        EFFECT_BEWILDERED_DAZE_5 = 452,
        EFFECT_DIVINE_CARESS_1 = 453,
        EFFECT_SABOTEUR = 454,
        EFFECT_TENUTO = 455,
        EFFECT_SPUR = 456,
        EFFECT_EFFLUX = 457,
        EFFECT_EARTHEN_ARMOR = 458,
        EFFECT_DIVINE_CARESS_2 = 459,
        EFFECT_BLOOD_RAGE = 460,
        EFFECT_IMPETUS = 461,
        EFFECT_CONSPIRATOR = 462,
        EFFECT_SEPULCHER = 463,
        EFFECT_ARCANE_CREST = 464,
        EFFECT_HAMANOHA = 465,
        EFFECT_DRAGON_BREAKER = 466,
        EFFECT_TRIPLE_SHOT = 467,
        EFFECT_STRIKING_FLOURISH = 468,
        EFFECT_PERPETUANCE = 469,
        EFFECT_IMMANENCE = 470,
        EFFECT_MIGAWARI = 471,
        EFFECT_TERNARY_FLOURISH = 472, // DNC 93
        EFFECT_MUDDLE = 473, // MOB EFFECT
        EFFECT_PROWESS = 474, // GROUNDS OF VALOR
        EFFECT_VOIDWATCHER = 475, // VOIDWATCH
        EFFECT_ENSPHERE = 476, // SPHERE
        EFFECT_SACROSANCTITY = 477, // WHM 95
        EFFECT_PALISADE = 478, // PLD 95
        EFFECT_SCARLET_DELIRIUM = 479, // DRK 95
        EFFECT_SCARLET_DELIRIUM_1 = 480, // DRK 95
        EFFECT_ABDHALJS_SEAL = 481,
        EFFECT_DECOY_SHOT = 482, // RNG 95
        EFFECT_HAGAKURE = 483, // SAM 95
        EFFECT_ISSEKIGAN = 484, // NIN 95
        EFFECT_UNBRIDLED_LEARNING = 485, // BLU 95
        EFFECT_COUNTER_BOOST = 486, //
        EFFECT_ENDRAIN = 487, // FENRIR 96
        EFFECT_ENASPIR = 488, // FENRIR 96
        EFFECT_AFTERGLOW = 489, // WS AFTEREFFECT
        EFFECT_BRAZEN_RUSH = 490, //
        EFFECT_INNER_STRENGTH = 491,
        EFFECT_ASYLUM = 492,
        EFFECT_SUBTLE_SORCERY = 493,
        EFFECT_STYMIE = 494,
        // EFFECT_NONE                     = 495,
        EFFECT_INTERVENE = 496,
        EFFECT_SOUL_ENSLAVEMENT = 497,
        EFFECT_UNLEASH = 498,
        EFFECT_CLARION_CALL = 499,
        EFFECT_OVERKILL = 500,
        EFFECT_YAEGASUMI = 501,
        EFFECT_MIKAGE = 502,
        EFFECT_FLY_HIGH = 503,
        EFFECT_ASTRAL_CONDUIT = 504,
        EFFECT_UNBRIDLED_WISDOM = 505,
        // EFFECT_NONE                     = 506,
        EFFECT_GRAND_PAS = 507,
        EFFECT_WIDENED_COMPASS = 508,
        EFFECT_ODYLLIC_SUBTERFUGE = 509,
        EFFECT_ERGON_MIGHT = 510,
        EFFECT_REIVE_MARK = 511,
        EFFECT_IONIS = 512,
        EFFECT_BOLSTER = 513,
        // EFFECT_NONE                     = 514,
        EFFECT_LASTING_EMANATION = 515,
        EFFECT_ECLIPTIC_ATTRITION = 516,
        EFFECT_COLLIMATED_FERVOR = 517,
        EFFECT_DEMATERIALIZE = 518,
        EFFECT_THEURGIC_FOCUS = 519,
        // EFFECT_NONE                     = 520,
        // EFFECT_NONE                     = 521,
        EFFECT_ELEMENTAL_SFORZO = 522,
        EFFECT_IGNIS = 523,
        EFFECT_GELUS = 524,
        EFFECT_FLABRA = 525,
        EFFECT_TELLUS = 526,
        EFFECT_SULPOR = 527,
        EFFECT_UNDA = 528,
        EFFECT_LUX = 529,
        EFFECT_TENEBRAE = 530,
        EFFECT_VALLATION = 531,
        EFFECT_SWORDPLAY = 532,
        EFFECT_PFLUG = 533,
        EFFECT_EMBOLDEN = 534,
        EFFECT_VALIANCE = 535,
        EFFECT_GAMBIT = 536,
        EFFECT_LIEMENT = 537,
        EFFECT_ONE_FOR_ALL = 538,
        EFFECT_GEO_REGEN = 539,
        EFFECT_GEO_POISON = 540,
        EFFECT_GEO_REFRESH = 541,
        EFFECT_GEO_STR_BOOST = 542,
        EFFECT_GEO_DEX_BOOST = 543,
        EFFECT_GEO_VIT_BOOST = 544,
        EFFECT_GEO_AGI_BOOST = 545,
        EFFECT_GEO_INT_BOOST = 546,
        EFFECT_GEO_MND_BOOST = 547,
        EFFECT_GEO_CHR_BOOST = 548,
        EFFECT_GEO_ATTACK_BOOST = 549,
        EFFECT_GEO_DEFENSE_BOOST = 550,
        EFFECT_GEO_MAGIC_ATK_BOOST = 551,
        EFFECT_GEO_MAGIC_DEF_BOOST = 552,
        EFFECT_GEO_ACCURACY_BOOST = 553,
        EFFECT_GEO_EVASION_BOOST = 554,
        EFFECT_GEO_MAGIC_ACC_BOOST = 555,
        EFFECT_GEO_MAGIC_EVASION_BOOST = 556,
        EFFECT_GEO_ATTACK_DOWN = 557,
        EFFECT_GEO_DEFENSE_DOWN = 558,
        EFFECT_GEO_MAGIC_ATK_DOWN = 559,
        EFFECT_GEO_MAGIC_DEF_DOWN = 560,
        EFFECT_GEO_ACCURACY_DOWN = 561,
        EFFECT_GEO_EVASION_DOWN = 562,
        EFFECT_GEO_MAGIC_ACC_DOWN = 563,
        EFFECT_GEO_MAGIC_EVASION_DOWN = 564,
        EFFECT_GEO_SLOW = 565,
        EFFECT_GEO_PARALYSIS = 566,
        EFFECT_GEO_WEIGHT = 567,
        EFFECT_FOIL = 568,
        EFFECT_BLAZE_OF_GLORY = 569,
        EFFECT_BATTUTA = 570,
        EFFECT_RAYKE = 571,
        EFFECT_AVOIDANCE_DOWN = 572,
        EFFECT_DELUGE_SPIKES = 573,
        EFFECT_FAST_CAST = 574,
        EFFECT_GESTATION = 575,
        EFFECT_DOUBT = 576, // Bully: Intimidation Enfeeble status
        EFFECT_CAIT_SITHS_FAVOR = 577,
        EFFECT_FISHY_INTUITION = 578,
        EFFECT_COMMITMENT = 579,
        EFFECT_GEO_HASTE = 580,
        EFFECT_FLURRY_II = 581,
        EFFECT_CONTRADANCE = 582,
        EFFECT_APOGEE = 583,
        EFFECT_ENTRUST = 584,
        EFFECT_COSTUME_II = 585,
        EFFECT_CURING_CONDUIT = 586,
        EFFECT_TP_BONUS = 587,
        EFFECT_FINISHING_MOVE_6 = 588,
        EFFECT_FIRESTORM_II = 589,
        EFFECT_HAILSTORM_II = 590,
        EFFECT_WINDSTORM_II = 591,
        EFFECT_SANDSTORM_II = 592,
        EFFECT_THUNDERSTORM_II = 593,
        EFFECT_RAINSTORM_II = 594,
        EFFECT_AURORASTORM_II = 595,
        EFFECT_VOIDSTORM_II = 596,
        EFFECT_INUNDATION = 597,
        EFFECT_CASCADE = 598,
        EFFECT_CONSUME_MANA = 599,
        EFFECT_RUNEISTS_ROLL = 600,
        EFFECT_CROOKED_CARDS = 601,
        EFFECT_VORSEAL = 602,
        EFFECT_ELVORSEAL = 603,
        EFFECT_MIGHTY_GUARD = 604,
        EFFECT_GALE_SPIKES = 605,
        EFFECT_CLOD_SPIKES = 606,
        EFFECT_GLINT_SPIKES = 607,
        EFFECT_NEGATE_VIRUS = 608,
        EFFECT_NEGATE_CURSE = 609,
        EFFECT_NEGATE_CHARM = 610,
        EFFECT_MAGIC_EVASION_BOOST = 611,
        EFFECT_COLURE_ACTIVE = 612,
        EFFECT_MUMORS_RADIANCE = 613,
        EFFECT_ULLEGORES_GLOOM = 614,
        EFFECT_BOOST_II = 615,
        EFFECT_ARTISANAL_KNOWLEDGE = 616,
        EFFECT_SACRIFICE = 617,
        EFFECT_EMPOROXS_GIFT = 618,
        EFFECT_SPIRIT_BOND = 619,
        EFFECT_AWAKEN = 620,
        EFFECT_MAJESTY = 621,
        EFFECT_GUARDING_RATE_BOOST = 622,
        EFFECT_RAMPART = 623,
        EFFECT_WINDS_BLESSING = 624,
        EFFECT_SIRENS_FAVOR = 625,
        EFFECT_NEGATE_SLEEP = 626,
        EFFECT_MOBILIZATION = 627,
        EFFECT_HOVER_SHOT = 628,
        EFFECT_MOOGLE_AMPLIFIER = 629,
        EFFECT_TAINT = 630,
        EFFECT_HAUNT = 631,
        EFFECT_BLACK_SANCTUS = 632,
        EFFECT_ANIMATED = 633,

        // Effect icons in packet can go from 0-767, so no custom effects should go in that range.

        // Purchased from Cruor Prospector
        EFFECT_ABYSSEA_STR = 768,
        EFFECT_ABYSSEA_DEX = 769,
        EFFECT_ABYSSEA_VIT = 770,
        EFFECT_ABYSSEA_AGI = 771,
        EFFECT_ABYSSEA_INT = 772,
        EFFECT_ABYSSEA_MND = 773,
        EFFECT_ABYSSEA_CHR = 774,
        EFFECT_ABYSSEA_HP = 775,
        EFFECT_ABYSSEA_MP = 776,

        // *Prowess increases not currently retail accurate.
        // GoV Prowess bonus effects, real effect at ID 474
        EFFECT_PROWESS_CASKET_RATE = 777, // (Unimplemented)
        EFFECT_PROWESS_SKILL_RATE = 778, // (Unimplemented)
        EFFECT_PROWESS_CRYSTAL_YIELD = 779, // (Unimplemented)
        EFFECT_PROWESS_TH = 780, // +1 per tier
        EFFECT_PROWESS_ATTACK_SPEED = 781, // *flat 4% for now
        EFFECT_PROWESS_HP_MP = 782, // Base 3% and another 1% per tier.
        EFFECT_PROWESS_ACC_RACC = 783, // *flat 4% for now
        EFFECT_PROWESS_ATT_RATT = 784, // *flat 4% for now
        EFFECT_PROWESS_MACC_MATK = 785, // *flat 4% for now
        EFFECT_PROWESS_CURE_POTENCY = 786, // *flat 4% for now
        EFFECT_PROWESS_WS_DMG = 787, // (Unimplemented) 2% per tier.
        EFFECT_PROWESS_KILLER = 788, // *flat +4 for now
                                     // End GoV Prowess fakery

        EFFECT_MARK_OF_SEED = 790, // Tracks 30 min timer in ACP mission "Those Who Lurk in Shadows (II)"
        EFFECT_ALL_MISS = 791, // All attacks miss (ie - Tiamat while flying)
        EFFECT_SUPER_BUFF = 792, // Boss buff (ie - Nidhogg "2hour")
        EFFECT_NINJUTSU_ELE_DEBUFF = 793,
        EFFECT_HEALING = 794,
        EFFECT_LEAVEGAME = 795,
        EFFECT_HASTE_SAMBA_HASTE = 796, // Small JA Haste given by Haste Samba on hit
        EFFECT_TELEPORT = 797,
        EFFECT_CHAINBOUND = 798,
        EFFECT_SKILLCHAIN = 799,
        EFFECT_DYNAMIS = 800,
        EFFECT_MEDITATE = 801, // Dummy effect for SAM Meditate JA
        EFFECT_ELEMENTALRES_DOWN = 802, // Elemental resistance down
        EFFECT_FULL_SPEED_AHEAD = 803, // Used to track Full Speed Ahead quest minigame
        EFFECT_HYSTERIA = 804, // Used for Hysteroanima to stop after readying a weaponskill with no msg.
        EFFECT_TOMAHAWK = 805, // Silent status effect inflicted by a Warrior using the "Tomahawk" job ability
        EFFECT_NUKE_WALL = 806, // Custom effect for NM type mobs only. Applied by elemental magic damage sources
    }
}
